SET NAMES utf8mb4;
UPDATE ohrm_i18n_language SET added=1, enabled=1 WHERE code='pt_BR';
SET @ptbr := (SELECT id FROM ohrm_i18n_language WHERE code='pt_BR' LIMIT 1);
UPDATE hs_hr_config SET value='pt_BR' WHERE name='admin.localization.default_language';
UPDATE hs_hr_config SET value='No' WHERE name='admin.localization.use_browser_language';
UPDATE hs_hr_config SET value='d/m/Y' WHERE name='admin.localization.default_date_format';
INSERT INTO ohrm_i18n_translate (lang_string_id, language_id, value, customized, version, modified_at) VALUES
(1, @ptbr, 'Adicionar cargo', 1, 'custom', NOW()),
(2, @ptbr, 'Editar cargo', 1, 'custom', NOW()),
(3, @ptbr, 'Cargos', 1, 'custom', NOW()),
(4, @ptbr, 'Locais', 1, 'custom', NOW()),
(5, @ptbr, 'Número de funcionários', 1, 'custom', NOW()),
(6, @ptbr, 'Adicionar local', 1, 'custom', NOW()),
(7, @ptbr, 'Endereço', 1, 'custom', NOW()),
(8, @ptbr, 'Configura??o de e-mail', 1, 'custom', NOW()),
(9, @ptbr, 'Correio enviado como', 1, 'custom', NOW()),
(10, @ptbr, 'Método de envio', 1, 'custom', NOW()),
(11, @ptbr, 'SECURESMTP', 1, 'custom', NOW()),
(12, @ptbr, 'SMTP', 1, 'custom', NOW()),
(13, @ptbr, 'Enviar e-mail', 1, 'custom', NOW()),
(14, @ptbr, 'Caminho para Sendmail', 1, 'custom', NOW()),
(15, @ptbr, 'AnfitriãoSMTP', 1, 'custom', NOW()),
(16, @ptbr, 'PortaSMTP', 1, 'custom', NOW()),
(17, @ptbr, 'Usar autenticaçãoSMTP', 1, 'custom', NOW()),
(18, @ptbr, 'UsuárioSMTP', 1, 'custom', NOW()),
(19, @ptbr, 'SenhaSMTP', 1, 'custom', NOW()),
(20, @ptbr, 'TLS', 1, 'custom', NOW()),
(21, @ptbr, 'Opcional - o servidor de e-mail requer o uso da segurançaTLS.', 1, 'custom', NOW()),
(22, @ptbr, 'Enviar e-mail de teste', 1, 'custom', NOW()),
(23, @ptbr, 'Endereço de e-mail de teste', 1, 'custom', NOW()),
(24, @ptbr, 'Assinantes', 1, 'custom', NOW()),
(25, @ptbr, 'Editar assinante', 1, 'custom', NOW()),
(26, @ptbr, 'Assinaturas de e-mail', 1, 'custom', NOW()),
(27, @ptbr, 'Tipo de notificação', 1, 'custom', NOW()),
(28, @ptbr, 'Adicionar assinante', 1, 'custom', NOW()),
(29, @ptbr, 'Editar status de emprego', 1, 'custom', NOW()),
(30, @ptbr, 'Adicionar status de emprego', 1, 'custom', NOW()),
(31, @ptbr, 'Descrição do trabalho', 1, 'custom', NOW()),
(32, @ptbr, 'Editar local', 1, 'custom', NOW()),
(33, @ptbr, 'Configuração do Módulo', 1, 'custom', NOW()),
(34, @ptbr, 'M?dulo de Administra??o', 1, 'custom', NOW()),
(35, @ptbr, 'M?dulo de Pessoas', 1, 'custom', NOW()),
(36, @ptbr, 'M?dulo de F?rias', 1, 'custom', NOW()),
(37, @ptbr, 'M?dulo de Ponto', 1, 'custom', NOW()),
(38, @ptbr, 'Módulo de recrutamento', 1, 'custom', NOW()),
(39, @ptbr, 'Módulo de Desempenho', 1, 'custom', NOW()),
(40, @ptbr, 'Módulo de Manutenção', 1, 'custom', NOW()),
(41, @ptbr, 'Editar nacionalidade', 1, 'custom', NOW()),
(42, @ptbr, 'Nacionalidades', 1, 'custom', NOW()),
(43, @ptbr, 'Adicionar nacionalidade', 1, 'custom', NOW()),
(44, @ptbr, 'Informa??es gerais', 1, 'custom', NOW()),
(45, @ptbr, 'Nome da organização', 1, 'custom', NOW()),
(46, @ptbr, 'Número de registro', 1, 'custom', NOW()),
(47, @ptbr, 'ImpostoID', 1, 'custom', NOW()),
(48, @ptbr, 'Editar unidade organizacional', 1, 'custom', NOW()),
(49, @ptbr, 'ID da unidade', 1, 'custom', NOW()),
(50, @ptbr, 'Estrutura Organizacional', 1, 'custom', NOW()),
(51, @ptbr, 'Adicionar unidade organizacional', 1, 'custom', NOW()),
(52, @ptbr, 'Esta unidade será adicionada em', 1, 'custom', NOW()),
(53, @ptbr, 'Adicionar nível salarial', 1, 'custom', NOW()),
(54, @ptbr, 'Editar moeda', 1, 'custom', NOW()),
(55, @ptbr, 'Salário Mínimo', 1, 'custom', NOW()),
(56, @ptbr, 'Salário Máximo', 1, 'custom', NOW()),
(57, @ptbr, 'Editar nível salarial', 1, 'custom', NOW()),
(58, @ptbr, 'Faixas salariais', 1, 'custom', NOW()),
(59, @ptbr, 'Adicionar moeda', 1, 'custom', NOW()),
(60, @ptbr, 'Editar usuário', 1, 'custom', NOW()),
(61, @ptbr, 'Adicionar usuário', 1, 'custom', NOW()),
(62, @ptbr, 'Editar turno de trabalho', 1, 'custom', NOW()),
(63, @ptbr, 'Nome do turno', 1, 'custom', NOW()),
(64, @ptbr, 'Duração por dia', 1, 'custom', NOW()),
(65, @ptbr, 'Turnos de trabalho', 1, 'custom', NOW()),
(66, @ptbr, 'Horas por dia', 1, 'custom', NOW()),
(67, @ptbr, 'E-mail de teste enviado', 1, 'custom', NOW()),
(68, @ptbr, 'E-mail de teste não enviado', 1, 'custom', NOW()),
(69, @ptbr, 'Funcionários Designados', 1, 'custom', NOW()),
(70, @ptbr, 'O nome da unidade organizacional deve ser exclusivo', 1, 'custom', NOW()),
(71, @ptbr, 'Deve ser superior ao salário mínimo', 1, 'custom', NOW()),
(72, @ptbr, 'Categorias de cargo', 1, 'custom', NOW()),
(73, @ptbr, 'Adicionar categoria de trabalho', 1, 'custom', NOW()),
(74, @ptbr, 'Editar categoria de trabalho', 1, 'custom', NOW()),
(75, @ptbr, 'Usuários do sistema', 1, 'custom', NOW()),
(76, @ptbr, 'Adicionar turno de trabalho', 1, 'custom', NOW()),
(77, @ptbr, 'Licen?as', 1, 'custom', NOW()),
(78, @ptbr, 'Localiza??o', 1, 'custom', NOW()),
(80, @ptbr, 'Formato de data', 1, 'custom', NOW()),
(81, @ptbr, 'Horas de trabalho', 1, 'custom', NOW()),
(82, @ptbr, 'Nome', 1, 'custom', NOW()),
(83, @ptbr, 'Cidade', 1, 'custom', NOW()),
(84, @ptbr, 'País', 1, 'custom', NOW()),
(85, @ptbr, 'Limpar', 1, 'custom', NOW()),
(86, @ptbr, 'Pesquisar', 1, 'custom', NOW()),
(87, @ptbr, 'Adicionar', 1, 'custom', NOW()),
(88, @ptbr, 'Telefone', 1, 'custom', NOW()),
(89, @ptbr, 'Estado/Província', 1, 'custom', NOW()),
(90, @ptbr, 'CEP / Código Postal', 1, 'custom', NOW()),
(91, @ptbr, 'Observação', 1, 'custom', NOW()),
(92, @ptbr, 'Cancelar', 1, 'custom', NOW()),
(93, @ptbr, 'Sim', 1, 'custom', NOW()),
(94, @ptbr, 'N?o', 1, 'custom', NOW()),
(95, @ptbr, 'E-mail', 1, 'custom', NOW()),
(96, @ptbr, 'Fax', 1, 'custom', NOW()),
(97, @ptbr, 'Nacionalidade', 1, 'custom', NOW()),
(98, @ptbr, 'Editar', 1, 'custom', NOW()),
(99, @ptbr, 'Endereço Rua 1', 1, 'custom', NOW()),
(100, @ptbr, 'Endereço Rua 2', 1, 'custom', NOW()),
(101, @ptbr, 'Descrição', 1, 'custom', NOW()),
(102, @ptbr, 'Moeda', 1, 'custom', NOW()),
(103, @ptbr, 'Moedas', 1, 'custom', NOW()),
(104, @ptbr, 'Editar educação', 1, 'custom', NOW()),
(105, @ptbr, 'Nível', 1, 'custom', NOW()),
(106, @ptbr, 'Escolaridade', 1, 'custom', NOW()),
(107, @ptbr, 'Adicionar educação', 1, 'custom', NOW()),
(108, @ptbr, 'Editar idioma', 1, 'custom', NOW()),
(109, @ptbr, 'Adicionar idioma', 1, 'custom', NOW()),
(110, @ptbr, 'Idiomas', 1, 'custom', NOW()),
(111, @ptbr, 'Editar licença', 1, 'custom', NOW()),
(112, @ptbr, 'Adicionar licença', 1, 'custom', NOW()),
(113, @ptbr, 'Editar associação', 1, 'custom', NOW()),
(114, @ptbr, 'Adicionar associação', 1, 'custom', NOW()),
(115, @ptbr, 'Associa??es', 1, 'custom', NOW()),
(116, @ptbr, 'Editar habilidade', 1, 'custom', NOW()),
(117, @ptbr, 'Adicionar habilidade', 1, 'custom', NOW()),
(118, @ptbr, 'Compet?ncias', 1, 'custom', NOW()),
(119, @ptbr, 'Função do usuário', 1, 'custom', NOW()),
(120, @ptbr, 'Status', 1, 'custom', NOW()),
(121, @ptbr, 'Usu?rio', 1, 'custom', NOW()),
(122, @ptbr, 'Nome do colaborador', 1, 'custom', NOW()),
(123, @ptbr, 'De', 1, 'custom', NOW()),
(124, @ptbr, 'Para', 1, 'custom', NOW()),
(125, @ptbr, 'Já existe', 1, 'custom', NOW()),
(126, @ptbr, 'O tempo deve ser depois do tempo', 1, 'custom', NOW()),
(127, @ptbr, 'Fracassado', 1, 'custom', NOW()),
(128, @ptbr, 'Não deve exceder caracteres{amount}', 1, 'custom', NOW()),
(129, @ptbr, 'Administra??o', 1, 'custom', NOW()),
(130, @ptbr, 'Obrigat?rio', 1, 'custom', NOW()),
(131, @ptbr, 'Salvar', 1, 'custom', NOW()),
(132, @ptbr, 'Deve ser uma data válida no formato hh:mm', 1, 'custom', NOW()),
(133, @ptbr, 'Categoria de trabalho', 1, 'custom', NOW()),
(135, @ptbr, 'Deve ser uma data válida no formato{format}', 1, 'custom', NOW()),
(136, @ptbr, 'Deve ser menor que{amount}', 1, 'custom', NOW()),
(137, @ptbr, 'Deve ser um número', 1, 'custom', NOW()),
(138, @ptbr, 'A data de término deve ser posterior à data de início', 1, 'custom', NOW()),
(139, @ptbr, 'O horário de término deve ser posterior ao horário de início', 1, 'custom', NOW()),
(140, @ptbr, 'Tamanho do anexo excedido', 1, 'custom', NOW()),
(141, @ptbr, 'Tipo de arquivo não permitido', 1, 'custom', NOW()),
(142, @ptbr, 'Situa??o do v?nculo', 1, 'custom', NOW()),
(143, @ptbr, 'Permite números e apenas + - / ( )', 1, 'custom', NOW()),
(144, @ptbr, 'A data de início deve ser anterior à data de término', 1, 'custom', NOW()),
(145, @ptbr, 'O horário de início deve ser antes do horário de término', 1, 'custom', NOW()),
(147, @ptbr, 'Deve ser superior ao valor mínimo', 1, 'custom', NOW()),
(148, @ptbr, 'ESS', 1, 'custom', NOW()),
(149, @ptbr, 'Ativado', 1, 'custom', NOW()),
(150, @ptbr, 'Desativado', 1, 'custom', NOW()),
(151, @ptbr, 'Editar anexo', 1, 'custom', NOW()),
(152, @ptbr, 'Ações', 1, 'custom', NOW()),
(153, @ptbr, 'Erro', 1, 'custom', NOW()),
(154, @ptbr, 'Tipo', 1, 'custom', NOW()),
(155, @ptbr, 'Download', 1, 'custom', NOW()),
(156, @ptbr, 'Selecione o arquivo', 1, 'custom', NOW()),
(157, @ptbr, 'Navegar', 1, 'custom', NOW()),
(159, @ptbr, 'Carregar', 1, 'custom', NOW()),
(160, @ptbr, 'Sucesso', 1, 'custom', NOW()),
(163, @ptbr, 'Matr?cula', 1, 'custom', NOW()),
(164, @ptbr, 'Eu ia', 1, 'custom', NOW()),
(165, @ptbr, 'Sobrenome', 1, 'custom', NOW()),
(166, @ptbr, 'Cargo', 1, 'custom', NOW()),
(167, @ptbr, 'Unidade', 1, 'custom', NOW()),
(168, @ptbr, 'Colaboradores atuais e antigos', 1, 'custom', NOW()),
(169, @ptbr, 'Somente ex-funcionários', 1, 'custom', NOW()),
(170, @ptbr, 'Somente colaboradores atuais', 1, 'custom', NOW()),
(171, @ptbr, 'Móvel', 1, 'custom', NOW()),
(172, @ptbr, 'Data de validade', 1, 'custom', NOW()),
(173, @ptbr, 'Data de adesão', 1, 'custom', NOW()),
(174, @ptbr, 'Localização', 1, 'custom', NOW()),
(175, @ptbr, 'Masculino', 1, 'custom', NOW()),
(176, @ptbr, 'Feminino', 1, 'custom', NOW()),
(177, @ptbr, 'Qualifica??es', 1, 'custom', NOW()),
(178, @ptbr, 'Estado', 1, 'custom', NOW()),
(179, @ptbr, 'Deve ser um número positivo', 1, 'custom', NOW()),
(180, @ptbr, 'Adicionar colaborador', 1, 'custom', NOW()),
(181, @ptbr, 'Nome do relatório', 1, 'custom', NOW()),
(182, @ptbr, 'Aviso', 1, 'custom', NOW()),
(183, @ptbr, 'Relat?rios de colaboradores', 1, 'custom', NOW()),
(184, @ptbr, 'Arquivo atual', 1, 'custom', NOW()),
(185, @ptbr, 'Substituir por', 1, 'custom', NOW()),
(186, @ptbr, 'Comentário', 1, 'custom', NOW()),
(187, @ptbr, 'Digite o comentário aqui', 1, 'custom', NOW()),
(188, @ptbr, 'Ano', 1, 'custom', NOW()),
(189, @ptbr, 'Data de início', 1, 'custom', NOW()),
(190, @ptbr, 'Data de término', 1, 'custom', NOW()),
(191, @ptbr, 'Comentários', 1, 'custom', NOW()),
(192, @ptbr, 'Digite comentários aqui', 1, 'custom', NOW()),
(193, @ptbr, 'Linguagem', 1, 'custom', NOW()),
(194, @ptbr, 'Classificação salarial', 1, 'custom', NOW()),
(195, @ptbr, 'Até a data deve ser posterior à data De', 1, 'custom', NOW()),
(196, @ptbr, '(Colaborador antigo)', 1, 'custom', NOW()),
(197, @ptbr, 'Primeiro nome', 1, 'custom', NOW()),
(198, @ptbr, 'Nome do meio', 1, 'custom', NOW()),
(199, @ptbr, 'Nome completo do colaborador', 1, 'custom', NOW()),
(200, @ptbr, 'Especificação do trabalho', 1, 'custom', NOW()),
(201, @ptbr, 'Anexos', 1, 'custom', NOW()),
(202, @ptbr, 'Nome do arquivo', 1, 'custom', NOW()),
(203, @ptbr, 'Tamanho', 1, 'custom', NOW()),
(204, @ptbr, 'Aceita jpg, .png, .gif até 1 MB. Dimensões recomendadas: 200px X 200px', 1, 'custom', NOW()),
(205, @ptbr, 'A data inicial deve ser anterior à data', 1, 'custom', NOW()),
(206, @ptbr, 'Deve ser menor que o limite superior', 1, 'custom', NOW()),
(207, @ptbr, 'Incluir cabeçalho', 1, 'custom', NOW()),
(208, @ptbr, 'Adicionar anexo', 1, 'custom', NOW()),
(209, @ptbr, 'Digite aqui', 1, 'custom', NOW()),
(210, @ptbr, 'Data', 1, 'custom', NOW()),
(211, @ptbr, 'Segunda-feira', 1, 'custom', NOW()),
(212, @ptbr, 'Ter?a-feira', 1, 'custom', NOW()),
(213, @ptbr, 'Quarta-feira', 1, 'custom', NOW()),
(214, @ptbr, 'Quinta-feira', 1, 'custom', NOW()),
(215, @ptbr, 'Sexta-feira', 1, 'custom', NOW()),
(216, @ptbr, 'S?bado', 1, 'custom', NOW()),
(217, @ptbr, 'Domingo', 1, 'custom', NOW()),
(218, @ptbr, 'Funcionário', 1, 'custom', NOW()),
(219, @ptbr, 'Gerar', 1, 'custom', NOW()),
(220, @ptbr, 'Da data', 1, 'custom', NOW()),
(221, @ptbr, 'A data', 1, 'custom', NOW()),
(222, @ptbr, 'Duração', 1, 'custom', NOW()),
(223, @ptbr, 'Solicitar', 1, 'custom', NOW()),
(224, @ptbr, 'Voltar', 1, 'custom', NOW()),
(225, @ptbr, 'Confirmar', 1, 'custom', NOW()),
(226, @ptbr, 'Nenhum funcionário correspondente', 1, 'custom', NOW()),
(227, @ptbr, 'Nenhum funcionário corresponde aos filtros selecionados', 1, 'custom', NOW()),
(228, @ptbr, 'OK', 1, 'custom', NOW()),
(229, @ptbr, 'F?rias', 1, 'custom', NOW()),
(230, @ptbr, 'Comente aqui', 1, 'custom', NOW()),
(231, @ptbr, 'De vez em quando deveria ser antes de vez', 1, 'custom', NOW()),
(232, @ptbr, '(Excluído)', 1, 'custom', NOW()),
(233, @ptbr, 'Adicionar comentário', 1, 'custom', NOW()),
(234, @ptbr, 'Aprovar', 1, 'custom', NOW()),
(235, @ptbr, 'Rejeitar', 1, 'custom', NOW()),
(236, @ptbr, '{contagem,plural, =0{No Records Found}um{(1) Record Found}outro{ (#) Records Found}}', 1, 'custom', NOW()),
(237, @ptbr, '{contagem,plural, =0{No Records Selected}um{(1) Record Selected}outro{(#) Records Selected}}', 1, 'custom', NOW()),
(238, @ptbr, 'Senha', 1, 'custom', NOW()),
(239, @ptbr, 'Para uma senha forte, use uma combinação de texto difícil de adivinhar com caracteres maiúsculos e minúsculos, símbolos e números', 1, 'custom', NOW()),
(240, @ptbr, 'Confirmar senha', 1, 'custom', NOW()),
(241, @ptbr, 'As senhas não coincidem', 1, 'custom', NOW()),
(242, @ptbr, 'Fraco', 1, 'custom', NOW()),
(243, @ptbr, 'Muito fraco', 1, 'custom', NOW()),
(244, @ptbr, 'Melhorar', 1, 'custom', NOW()),
(245, @ptbr, 'Mais forte', 1, 'custom', NOW()),
(246, @ptbr, 'Sobre', 1, 'custom', NOW()),
(247, @ptbr, 'Apoiar', 1, 'custom', NOW()),
(248, @ptbr, 'Alterar senha', 1, 'custom', NOW()),
(249, @ptbr, 'Sair', 1, 'custom', NOW()),
(250, @ptbr, 'Nenhum registro encontrado', 1, 'custom', NOW()),
(251, @ptbr, 'Alterar a senha ?', 1, 'custom', NOW()),
(252, @ptbr, 'Digite a descrição aqui', 1, 'custom', NOW()),
(253, @ptbr, 'Adicionar nota', 1, 'custom', NOW()),
(254, @ptbr, 'Atualizado com sucesso', 1, 'custom', NOW()),
(255, @ptbr, 'Salvo com sucesso', 1, 'custom', NOW()),
(256, @ptbr, 'Notas', 1, 'custom', NOW()),
(257, @ptbr, 'Digite aqui...', 1, 'custom', NOW()),
(258, @ptbr, 'Cargo', 1, 'custom', NOW()),
(259, @ptbr, 'Não, cancelar', 1, 'custom', NOW()),
(260, @ptbr, 'Gerenciamento de usu?rios', 1, 'custom', NOW()),
(261, @ptbr, 'Informa??es do projeto', 1, 'custom', NOW()),
(262, @ptbr, 'Organiza??o', 1, 'custom', NOW()),
(263, @ptbr, 'Usu?rios', 1, 'custom', NOW()),
(264, @ptbr, 'Configura??o', 1, 'custom', NOW()),
(265, @ptbr, 'Pacotes de idioma', 1, 'custom', NOW()),
(266, @ptbr, 'M?dulos', 1, 'custom', NOW()),
(267, @ptbr, 'Registrar cliente OAuth', 1, 'custom', NOW()),
(268, @ptbr, 'Autenticação de mídia social', 1, 'custom', NOW()),
(269, @ptbr, 'Lista de colaboradores', 1, 'custom', NOW()),
(270, @ptbr, 'Relat?rios', 1, 'custom', NOW()),
(271, @ptbr, 'Pessoas', 1, 'custom', NOW()),
(272, @ptbr, 'Recrutamento', 1, 'custom', NOW()),
(273, @ptbr, 'Ponto', 1, 'custom', NOW()),
(274, @ptbr, 'Meus Dados', 1, 'custom', NOW()),
(275, @ptbr, 'Desempenho', 1, 'custom', NOW()),
(276, @ptbr, 'Painel', 1, 'custom', NOW()),
(277, @ptbr, 'Diret?rio', 1, 'custom', NOW()),
(278, @ptbr, 'Comunicados', 1, 'custom', NOW()),
(279, @ptbr, 'Manuten??o', 1, 'custom', NOW()),
(280, @ptbr, 'Minhas folhas de ponto', 1, 'custom', NOW()),
(281, @ptbr, 'Meus registros', 1, 'custom', NOW()),
(282, @ptbr, 'Folhas de ponto dos colaboradores', 1, 'custom', NOW()),
(283, @ptbr, 'Folhas de ponto', 1, 'custom', NOW()),
(284, @ptbr, 'Entrada/Sa?da', 1, 'custom', NOW()),
(285, @ptbr, 'Registros de colaboradores', 1, 'custom', NOW()),
(286, @ptbr, 'Frequ?ncia', 1, 'custom', NOW()),
(287, @ptbr, 'Clientes', 1, 'custom', NOW()),
(288, @ptbr, 'Projetos', 1, 'custom', NOW()),
(289, @ptbr, 'Relat?rios de projeto', 1, 'custom', NOW()),
(290, @ptbr, 'Vagas', 1, 'custom', NOW()),
(291, @ptbr, 'Candidatos', 1, 'custom', NOW()),
(292, @ptbr, 'KPIs', 1, 'custom', NOW()),
(293, @ptbr, 'Gerenciar avalia??es', 1, 'custom', NOW()),
(294, @ptbr, 'Minhas avalia??es', 1, 'custom', NOW()),
(295, @ptbr, 'Meus acompanhamentos', 1, 'custom', NOW()),
(296, @ptbr, 'Lista de revisão', 1, 'custom', NOW()),
(297, @ptbr, 'Acompanhamentos', 1, 'custom', NOW()),
(298, @ptbr, 'Acompanhamentos de colaboradores', 1, 'custom', NOW()),
(299, @ptbr, 'Registros de candidatos', 1, 'custom', NOW()),
(300, @ptbr, 'Acessar registros', 1, 'custom', NOW()),
(301, @ptbr, 'Eliminar registros', 1, 'custom', NOW()),
(302, @ptbr, 'Estrutura', 1, 'custom', NOW()),
(303, @ptbr, 'Dom', 1, 'custom', NOW()),
(304, @ptbr, 'Seg', 1, 'custom', NOW()),
(305, @ptbr, 'Ter', 1, 'custom', NOW()),
(306, @ptbr, 'Qua', 1, 'custom', NOW()),
(307, @ptbr, 'Qui', 1, 'custom', NOW()),
(308, @ptbr, 'Sex', 1, 'custom', NOW()),
(309, @ptbr, 'S?b', 1, 'custom', NOW()),
(310, @ptbr, 'Executado por', 1, 'custom', NOW()),
(311, @ptbr, 'Adicionar outro', 1, 'custom', NOW()),
(312, @ptbr, 'Visualizar', 1, 'custom', NOW()),
(313, @ptbr, 'Resumo de frequ?ncia', 1, 'custom', NOW()),
(314, @ptbr, 'Minhas f?rias', 1, 'custom', NOW()),
(315, @ptbr, 'Meus saldos', 1, 'custom', NOW()),
(316, @ptbr, 'Adicionar saldos', 1, 'custom', NOW()),
(317, @ptbr, 'Configurar', 1, 'custom', NOW()),
(318, @ptbr, 'Saldos do colaborador', 1, 'custom', NOW()),
(319, @ptbr, 'Saldos', 1, 'custom', NOW()),
(320, @ptbr, 'E-mail de trabalho', 1, 'custom', NOW()),
(321, @ptbr, 'Outro e-mail', 1, 'custom', NOW()),
(322, @ptbr, 'nome da empresa', 1, 'custom', NOW()),
(323, @ptbr, 'Versão', 1, 'custom', NOW()),
(324, @ptbr, 'Funcionários Ativos', 1, 'custom', NOW()),
(325, @ptbr, 'Funcionários demitidos', 1, 'custom', NOW()),
(326, @ptbr, 'Tem certeza?', 1, 'custom', NOW()),
(327, @ptbr, 'O registro selecionado será excluído permanentemente. Tem certeza de que deseja continuar?', 1, 'custom', NOW()),
(328, @ptbr, 'Sim, excluir', 1, 'custom', NOW()),
(329, @ptbr, 'Mantenha-se atualizado', 1, 'custom', NOW()),
(330, @ptbr, 'Excluir atual', 1, 'custom', NOW()),
(331, @ptbr, 'Substituir atual', 1, 'custom', NOW()),
(332, @ptbr, 'Módulo Proibido', 1, 'custom', NOW()),
(333, @ptbr, 'A página que você está tentando acessar tem acesso restrito', 1, 'custom', NOW()),
(334, @ptbr, 'Lançamento em breve', 1, 'custom', NOW()),
(337, @ptbr, 'Clique aqui', 1, 'custom', NOW()),
(338, @ptbr, 'Pedido ruim', 1, 'custom', NOW()),
(339, @ptbr, 'Dados pessoais', 1, 'custom', NOW()),
(340, @ptbr, 'Contatos de emerg?ncia', 1, 'custom', NOW()),
(341, @ptbr, 'Dependentes', 1, 'custom', NOW()),
(342, @ptbr, 'Imigra??o', 1, 'custom', NOW()),
(343, @ptbr, 'Sal?rio', 1, 'custom', NOW()),
(344, @ptbr, 'Reporta-se a', 1, 'custom', NOW()),
(345, @ptbr, 'Isenções fiscais', 1, 'custom', NOW()),
(346, @ptbr, 'Informações', 1, 'custom', NOW()),
(347, @ptbr, 'Formato esperado: admin@example.com', 1, 'custom', NOW()),
(348, @ptbr, 'Enviar', 1, 'custom', NOW()),
(349, @ptbr, 'Período', 1, 'custom', NOW()),
(350, @ptbr, 'aaaa-mm-dd', 1, 'custom', NOW()),
(351, @ptbr, 'Não pode ser excluído', 1, 'custom', NOW()),
(352, @ptbr, 'Exclu?do com sucesso', 1, 'custom', NOW()),
(353, @ptbr, 'Total', 1, 'custom', NOW()),
(354, @ptbr, 'Procurando....', 1, 'custom', NOW()),
(355, @ptbr, 'Nenhum arquivo escolhido', 1, 'custom', NOW()),
(356, @ptbr, 'Nenhum arquivo selecionado', 1, 'custom', NOW()),
(357, @ptbr, 'Digite para obter dicas...', 1, 'custom', NOW()),
(358, @ptbr, '-- Selecionar --', 1, 'custom', NOW()),
(359, @ptbr, 'Erro inesperado!', 1, 'custom', NOW()),
(360, @ptbr, 'Excluir selecionado', 1, 'custom', NOW()),
(361, @ptbr, 'Identidade visual', 1, 'custom', NOW()),
(362, @ptbr, 'Mais', 1, 'custom', NOW()),
(363, @ptbr, 'Deve ser maior que o limite inferior', 1, 'custom', NOW()),
(364, @ptbr, 'Menor que', 1, 'custom', NOW()),
(365, @ptbr, 'Maior que', 1, 'custom', NOW()),
(366, @ptbr, 'Faixa', 1, 'custom', NOW()),
(367, @ptbr, 'Campos personalizados', 1, 'custom', NOW()),
(368, @ptbr, 'Número restante de campos personalizados:', 1, 'custom', NOW()),
(369, @ptbr, 'Todos os campos personalizados estão em uso', 1, 'custom', NOW()),
(370, @ptbr, 'Nome do campo personalizado', 1, 'custom', NOW()),
(371, @ptbr, 'Tela', 1, 'custom', NOW()),
(372, @ptbr, 'Tipo de campo', 1, 'custom', NOW()),
(373, @ptbr, 'Campos personalizados em uso', 1, 'custom', NOW()),
(374, @ptbr, 'Editar campo personalizado', 1, 'custom', NOW()),
(375, @ptbr, 'Nome do campo', 1, 'custom', NOW()),
(376, @ptbr, 'Selecione Opções', 1, 'custom', NOW()),
(377, @ptbr, 'Insira as opções permitidas separadas por vírgulas', 1, 'custom', NOW()),
(378, @ptbr, 'Adicionar campo personalizado', 1, 'custom', NOW()),
(379, @ptbr, 'Importa??o de dados', 1, 'custom', NOW()),
(380, @ptbr, 'A ordem das colunas não deve ser alterada', 1, 'custom', NOW()),
(381, @ptbr, 'Nome e Sobrenome são obrigatórios', 1, 'custom', NOW()),
(382, @ptbr, 'Todos os campos de data devem estar no formatoYYYY-MM-DD', 1, 'custom', NOW()),
(383, @ptbr, 'Se o gênero for especificado, o valor deverá ser Masculino ou Feminino', 1, 'custom', NOW()),
(384, @ptbr, 'Cada arquivo de importação deve ser configurado para 100 registros ou menos', 1, 'custom', NOW()),
(385, @ptbr, 'Vários arquivos de importação podem ser necessários', 1, 'custom', NOW()),
(386, @ptbr, 'Exemplo de arquivoCSV', 1, 'custom', NOW()),
(388, @ptbr, 'Informa??es do colaborador', 1, 'custom', NOW()),
(389, @ptbr, 'Incluir', 1, 'custom', NOW()),
(390, @ptbr, 'Nome do supervisor', 1, 'custom', NOW()),
(391, @ptbr, 'Primeiro (e nome do meio)', 1, 'custom', NOW()),
(392, @ptbr, 'Supervisor', 1, 'custom', NOW()),
(393, @ptbr, 'Dados de contato', 1, 'custom', NOW()),
(394, @ptbr, 'Rua 1', 1, 'custom', NOW()),
(395, @ptbr, 'Rua 2', 1, 'custom', NOW()),
(396, @ptbr, 'Telefone', 1, 'custom', NOW()),
(397, @ptbr, 'Lar', 1, 'custom', NOW()),
(398, @ptbr, 'Trabalhar', 1, 'custom', NOW()),
(399, @ptbr, 'Dependentes Atribuídos', 1, 'custom', NOW()),
(400, @ptbr, 'Relação', 1, 'custom', NOW()),
(401, @ptbr, 'Data de nascimento', 1, 'custom', NOW()),
(402, @ptbr, 'Contatos de emergência atribuídos', 1, 'custom', NOW()),
(403, @ptbr, 'Telefone residencial', 1, 'custom', NOW()),
(404, @ptbr, 'Telefone de trabalho', 1, 'custom', NOW()),
(405, @ptbr, 'Registros de Imigração Atribuídos', 1, 'custom', NOW()),
(406, @ptbr, 'Documento', 1, 'custom', NOW()),
(407, @ptbr, 'Número', 1, 'custom', NOW()),
(408, @ptbr, 'Emitida pela', 1, 'custom', NOW()),
(409, @ptbr, 'Data de emissão', 1, 'custom', NOW()),
(410, @ptbr, 'Detalhes do trabalho', 1, 'custom', NOW()),
(411, @ptbr, 'Incluir detalhes do contrato de trabalho', 1, 'custom', NOW()),
(412, @ptbr, 'Data de início do contrato', 1, 'custom', NOW()),
(413, @ptbr, 'Data de término do contrato', 1, 'custom', NOW()),
(414, @ptbr, 'Detalhes do contrato', 1, 'custom', NOW()),
(415, @ptbr, 'Associações atribuídas', 1, 'custom', NOW()),
(416, @ptbr, 'Associação', 1, 'custom', NOW()),
(417, @ptbr, 'Assinatura paga por', 1, 'custom', NOW()),
(418, @ptbr, 'Valor da assinatura', 1, 'custom', NOW()),
(419, @ptbr, 'Data de início da assinatura', 1, 'custom', NOW()),
(420, @ptbr, 'Data de renovação da assinatura', 1, 'custom', NOW()),
(421, @ptbr, 'Outro documento', 1, 'custom', NOW()),
(422, @ptbr, 'N?mero da CNH', 1, 'custom', NOW()),
(423, @ptbr, 'Validade da CNH', 1, 'custom', NOW()),
(424, @ptbr, 'NúmeroSSN', 1, 'custom', NOW()),
(425, @ptbr, 'NúmeroSIN', 1, 'custom', NOW()),
(426, @ptbr, 'Estado civil', 1, 'custom', NOW()),
(427, @ptbr, 'G?nero', 1, 'custom', NOW()),
(428, @ptbr, 'Serviço militar', 1, 'custom', NOW()),
(429, @ptbr, 'Fumante', 1, 'custom', NOW()),
(430, @ptbr, 'O ID do funcionário já existe', 1, 'custom', NOW()),
(431, @ptbr, 'Alterar foto do perfil', 1, 'custom', NOW()),
(432, @ptbr, 'Reporta-se a', 1, 'custom', NOW()),
(433, @ptbr, 'Componente Salarial', 1, 'custom', NOW()),
(435, @ptbr, 'Frequência de pagamento', 1, 'custom', NOW()),
(436, @ptbr, 'Valor do depósito direto', 1, 'custom', NOW()),
(437, @ptbr, 'Imposto de Renda Federal', 1, 'custom', NOW()),
(438, @ptbr, 'Isenções', 1, 'custom', NOW()),
(439, @ptbr, 'Estado de desemprego', 1, 'custom', NOW()),
(440, @ptbr, 'Estado de trabalho', 1, 'custom', NOW()),
(441, @ptbr, 'Criar detalhes de login', 1, 'custom', NOW()),
(442, @ptbr, 'Campos opcionais', 1, 'custom', NOW()),
(443, @ptbr, 'Mostrar campos obsoletos', 1, 'custom', NOW()),
(444, @ptbr, 'Mostrar apelido, fumante e serviço militar em dados pessoais', 1, 'custom', NOW()),
(445, @ptbr, 'Informações específicas do país', 1, 'custom', NOW()),
(446, @ptbr, 'Mostrar campoSSNem detalhes pessoais', 1, 'custom', NOW()),
(447, @ptbr, 'Mostrar campoSINem detalhes pessoais', 1, 'custom', NOW()),
(448, @ptbr, 'Mostrar menu de isenções fiscaisUS', 1, 'custom', NOW()),
(449, @ptbr, 'Editar método de relatório', 1, 'custom', NOW()),
(450, @ptbr, 'Adicionar método de relatório', 1, 'custom', NOW()),
(451, @ptbr, 'Editar relatório', 1, 'custom', NOW()),
(452, @ptbr, 'M?todos de relat?rio', 1, 'custom', NOW()),
(453, @ptbr, 'Método(s) de relatório em uso', 1, 'custom', NOW()),
(454, @ptbr, 'Critérios de seleção', 1, 'custom', NOW()),
(455, @ptbr, 'Campos de exibição', 1, 'custom', NOW()),
(456, @ptbr, 'Selecione Exibir grupo de campos', 1, 'custom', NOW()),
(457, @ptbr, 'Selecione o campo de exibição', 1, 'custom', NOW()),
(458, @ptbr, 'Pelo menos um campo de exibição deve ser adicionado', 1, 'custom', NOW()),
(459, @ptbr, 'Adicionar relatório', 1, 'custom', NOW()),
(460, @ptbr, 'Editar motivo da rescisão', 1, 'custom', NOW()),
(461, @ptbr, 'Adicionar motivo de rescisão', 1, 'custom', NOW()),
(462, @ptbr, 'Motivos de desligamento', 1, 'custom', NOW()),
(463, @ptbr, 'Motivo(s) de rescisão em uso', 1, 'custom', NOW()),
(464, @ptbr, 'Atualizar senha', 1, 'custom', NOW()),
(465, @ptbr, 'Senha atual', 1, 'custom', NOW()),
(466, @ptbr, 'A senha atual está incorreta', 1, 'custom', NOW()),
(467, @ptbr, 'Editar Dependente', 1, 'custom', NOW()),
(468, @ptbr, 'Por favor especifique', 1, 'custom', NOW()),
(469, @ptbr, 'Criança', 1, 'custom', NOW()),
(470, @ptbr, 'Outro', 1, 'custom', NOW()),
(471, @ptbr, 'Instituto', 1, 'custom', NOW()),
(472, @ptbr, 'Major/Especialização', 1, 'custom', NOW()),
(473, @ptbr, 'GPA/Pontuação', 1, 'custom', NOW()),
(474, @ptbr, 'Editar contato de emergência', 1, 'custom', NOW()),
(475, @ptbr, 'É necessário pelo menos um número de telefone', 1, 'custom', NOW()),
(476, @ptbr, 'Método de relatório', 1, 'custom', NOW()),
(477, @ptbr, 'Editar Imigração', 1, 'custom', NOW()),
(478, @ptbr, 'Passaporte', 1, 'custom', NOW()),
(479, @ptbr, 'Visa', 1, 'custom', NOW()),
(480, @ptbr, 'Status Elegível', 1, 'custom', NOW()),
(481, @ptbr, 'Data de revisão elegível', 1, 'custom', NOW()),
(482, @ptbr, 'A data de validade deve ser posterior à data de emissão', 1, 'custom', NOW()),
(483, @ptbr, 'Fluência', 1, 'custom', NOW()),
(484, @ptbr, 'Competência', 1, 'custom', NOW()),
(485, @ptbr, 'Tipo de licença', 1, 'custom', NOW()),
(486, @ptbr, 'Número de licença', 1, 'custom', NOW()),
(487, @ptbr, 'A data de renovação deve ser posterior à data de início', 1, 'custom', NOW()),
(488, @ptbr, 'Editar componente salarial', 1, 'custom', NOW()),
(489, @ptbr, 'Componentes salariais atribuídos', 1, 'custom', NOW()),
(490, @ptbr, 'Incluir detalhes de depósito direto', 1, 'custom', NOW()),
(491, @ptbr, 'Número de conta', 1, 'custom', NOW()),
(492, @ptbr, 'Tipo de conta', 1, 'custom', NOW()),
(493, @ptbr, 'Número de roteamento', 1, 'custom', NOW()),
(494, @ptbr, 'Habilidade', 1, 'custom', NOW()),
(495, @ptbr, 'Anos de experiência', 1, 'custom', NOW()),
(496, @ptbr, 'Empresa', 1, 'custom', NOW()),
(497, @ptbr, 'Licença', 1, 'custom', NOW()),
(498, @ptbr, 'Subordinados Designados', 1, 'custom', NOW()),
(499, @ptbr, 'Supervisores Designados', 1, 'custom', NOW()),
(500, @ptbr, 'Experiência Profissional', 1, 'custom', NOW()),
(501, @ptbr, 'Adicionar experiência profissional', 1, 'custom', NOW()),
(502, @ptbr, 'Data adicionada', 1, 'custom', NOW()),
(503, @ptbr, 'Adicionado por', 1, 'custom', NOW()),
(504, @ptbr, 'Deve estar dentro dos valores Mín/Máx.', 1, 'custom', NOW()),
(505, @ptbr, 'Adicionar Imigração', 1, 'custom', NOW()),
(506, @ptbr, 'Adicionar Dependente', 1, 'custom', NOW()),
(507, @ptbr, 'Salvar contato de emergência', 1, 'custom', NOW()),
(508, @ptbr, 'Rescindir o emprego', 1, 'custom', NOW()),
(509, @ptbr, 'Data de rescisão', 1, 'custom', NOW()),
(510, @ptbr, 'Motivo da Rescisão', 1, 'custom', NOW()),
(511, @ptbr, 'Apelido', 1, 'custom', NOW()),
(512, @ptbr, 'Pessoal', 1, 'custom', NOW()),
(513, @ptbr, 'Ativar Emprego', 1, 'custom', NOW()),
(514, @ptbr, 'Sobrenome', 1, 'custom', NOW()),
(515, @ptbr, 'Primeiro nome', 1, 'custom', NOW()),
(516, @ptbr, 'Nome do meio', 1, 'custom', NOW()),
(517, @ptbr, 'Status de elegibilidade', 1, 'custom', NOW()),
(518, @ptbr, 'Data de revisão de elegibilidade', 1, 'custom', NOW()),
(519, @ptbr, 'Tipo de documento', 1, 'custom', NOW()),
(520, @ptbr, 'Nota de Rescisão', 1, 'custom', NOW()),
(521, @ptbr, 'Número da conta de depósito direto', 1, 'custom', NOW()),
(522, @ptbr, 'Tipo de conta de depósito direto', 1, 'custom', NOW()),
(524, @ptbr, 'Pontuação', 1, 'custom', NOW()),
(525, @ptbr, 'Texto ou Número', 1, 'custom', NOW()),
(526, @ptbr, 'Suspenso', 1, 'custom', NOW()),
(527, @ptbr, 'Supervisores', 1, 'custom', NOW()),
(528, @ptbr, 'Subordinados', 1, 'custom', NOW()),
(529, @ptbr, 'Período de serviço', 1, 'custom', NOW()),
(530, @ptbr, 'Faixa etária', 1, 'custom', NOW()),
(531, @ptbr, 'Rescisão/ativação de funcionário', 1, 'custom', NOW()),
(532, @ptbr, 'Terminado em', 1, 'custom', NOW()),
(533, @ptbr, 'E-mail comercial e outro e-mail não podem ser iguais', 1, 'custom', NOW()),
(534, @ptbr, 'Entrou antes', 1, 'custom', NOW()),
(535, @ptbr, 'Entrou depois', 1, 'custom', NOW()),
(536, @ptbr, 'Juntou-se no meio', 1, 'custom', NOW()),
(537, @ptbr, 'Dia inteiro/meio dia', 1, 'custom', NOW()),
(538, @ptbr, 'Repete anualmente', 1, 'custom', NOW()),
(539, @ptbr, 'Editar feriado', 1, 'custom', NOW()),
(540, @ptbr, 'Feriados', 1, 'custom', NOW()),
(541, @ptbr, 'Adicionar feriado', 1, 'custom', NOW()),
(542, @ptbr, 'Dia inteiro', 1, 'custom', NOW()),
(543, @ptbr, 'Per?odo de f?rias', 1, 'custom', NOW()),
(544, @ptbr, 'Mês de início', 1, 'custom', NOW()),
(545, @ptbr, 'Período de licença atual', 1, 'custom', NOW()),
(546, @ptbr, 'Ano seguinte', 1, 'custom', NOW()),
(547, @ptbr, 'Semana de trabalho', 1, 'custom', NOW()),
(548, @ptbr, 'Pelo menos um dia deve ser um dia útil', 1, 'custom', NOW()),
(549, @ptbr, 'Adicionar direito a licença', 1, 'custom', NOW()),
(550, @ptbr, 'adicionar à', 1, 'custom', NOW()),
(551, @ptbr, 'Funcionário individual', 1, 'custom', NOW()),
(552, @ptbr, 'Vários funcionários', 1, 'custom', NOW()),
(553, @ptbr, '{empMatchCount,plural, =0{Matches no employee}um{Matches (1) employee}outro{matches (#) employees}}', 1, 'custom', NOW()),
(554, @ptbr, 'Nenhum tipo de licença definido', 1, 'custom', NOW()),
(555, @ptbr, 'Deve ser um número com até 2 casas decimais', 1, 'custom', NOW()),
(556, @ptbr, 'Editar direito a licença', 1, 'custom', NOW()),
(557, @ptbr, 'Direito', 1, 'custom', NOW()),
(558, @ptbr, 'O valor usado excede o valor atual', 1, 'custom', NOW()),
(559, @ptbr, 'Direitos de licença', 1, 'custom', NOW()),
(560, @ptbr, 'Meus direitos de licença', 1, 'custom', NOW()),
(561, @ptbr, 'O direito é situacional?', 1, 'custom', NOW()),
(562, @ptbr, 'Adicionar tipo de licença', 1, 'custom', NOW()),
(563, @ptbr, 'Editar tipo de licença', 1, 'custom', NOW()),
(564, @ptbr, 'Tipos de f?rias', 1, 'custom', NOW()),
(565, @ptbr, 'Relatório de utilização e direitos de licença', 1, 'custom', NOW()),
(566, @ptbr, 'Gerar para', 1, 'custom', NOW()),
(567, @ptbr, 'Tipo de licença', 1, 'custom', NOW()),
(568, @ptbr, 'Incluir ex-funcionários', 1, 'custom', NOW()),
(569, @ptbr, 'Meus direitos de licença e relatório de uso', 1, 'custom', NOW()),
(570, @ptbr, 'Solicitar f?rias', 1, 'custom', NOW()),
(571, @ptbr, 'Nenhum tipo de licença com saldo de licença', 1, 'custom', NOW()),
(572, @ptbr, 'Dias parciais', 1, 'custom', NOW()),
(573, @ptbr, 'Atribuir f?rias', 1, 'custom', NOW()),
(574, @ptbr, 'Dia de início', 1, 'custom', NOW()),
(575, @ptbr, 'Fim do dia', 1, 'custom', NOW()),
(576, @ptbr, 'Atribuir', 1, 'custom', NOW()),
(577, @ptbr, 'Lista de f?rias', 1, 'custom', NOW()),
(578, @ptbr, 'Mostrar licença com status', 1, 'custom', NOW()),
(579, @ptbr, 'Detalhes do meu pedido de licença', 1, 'custom', NOW()),
(580, @ptbr, 'Deixe detalhes da solicitação', 1, 'custom', NOW()),
(581, @ptbr, 'Minha lista de licenças', 1, 'custom', NOW()),
(582, @ptbr, 'Atualizando direito', 1, 'custom', NOW()),
(583, @ptbr, 'Funcionários correspondentes', 1, 'custom', NOW()),
(584, @ptbr, 'O direito a férias selecionado será aplicado aos seguintes funcionários.', 1, 'custom', NOW()),
(585, @ptbr, 'Antigo direito', 1, 'custom', NOW()),
(586, @ptbr, 'Novo direito', 1, 'custom', NOW()),
(587, @ptbr, 'Licença Situacional', 1, 'custom', NOW()),
(588, @ptbr, 'Essas licenças serão excluídas dos relatórios, a menos que haja alguma atividade. Por exemplo licença maternidade, licença para serviço de júri.', 1, 'custom', NOW()),
(589, @ptbr, 'Confirmar atribuição de licença', 1, 'custom', NOW()),
(590, @ptbr, 'O funcionário não tem saldo de férias suficiente para solicitação de licença.', 1, 'custom', NOW()),
(591, @ptbr, 'Clique emOKpara confirmar a atribuição de licença.', 1, 'custom', NOW()),
(592, @ptbr, 'O valor de direito existente{oldvalue}será atualizado para{newvalue}', 1, 'custom', NOW()),
(593, @ptbr, 'Sair do saldo', 1, 'custom', NOW()),
(594, @ptbr, 'Saldo insuficiente', 1, 'custom', NOW()),
(595, @ptbr, 'Saldo de licença insuficiente', 1, 'custom', NOW()),
(596, @ptbr, 'Equilíbrio', 1, 'custom', NOW()),
(597, @ptbr, 'Dias', 1, 'custom', NOW()),
(598, @ptbr, 'Saldo disponível', 1, 'custom', NOW()),
(599, @ptbr, 'Deixe detalhes do saldo', 1, 'custom', NOW()),
(600, @ptbr, 'A partir da data', 1, 'custom', NOW()),
(601, @ptbr, 'Direito total', 1, 'custom', NOW()),
(602, @ptbr, 'Sair do status', 1, 'custom', NOW()),
(603, @ptbr, 'Levado', 1, 'custom', NOW()),
(604, @ptbr, 'Agendado', 1, 'custom', NOW()),
(605, @ptbr, 'Aprovação pendente', 1, 'custom', NOW()),
(606, @ptbr, '{ação, seleção,APPROVE{{contagem, plural, =0{You are about to Approve no Leave Requests}=1{You are about to Approve 1 Leave Request}outro{You are about to Approve # Leave Requests}}}REJECT{{contagem, plural, =0{You are about to Reject no Leave Requests}=1{You are about to Reject 1 Leave Request}outro{You are about to Reject # Leave Requests}}} outro {{contagem, plural, =0{You are about to Cancel no Leave Requests}=1{You are about to Cancel 1 Leave Request}outro{You are about to Cancel # Leave Requests}}} }', 1, 'custom', NOW()),
(607, @ptbr, 'Tem certeza de que deseja continuar?', 1, 'custom', NOW()),
(608, @ptbr, 'Sim, confirme', 1, 'custom', NOW()),
(609, @ptbr, 'Deixe comentários sobre solicitação', 1, 'custom', NOW()),
(610, @ptbr, 'Nº de horas', 1, 'custom', NOW()),
(611, @ptbr, 'Duração do turno de trabalho excedida devido às seguintes solicitações de licença', 1, 'custom', NOW()),
(612, @ptbr, 'Solicitações de licença sobrepostas encontradas', 1, 'custom', NOW()),
(613, @ptbr, 'A duração deve ser menor que a duração do turno de trabalho', 1, 'custom', NOW()),
(614, @ptbr, 'Meio Dia - Manhã', 1, 'custom', NOW()),
(615, @ptbr, 'Meio Dia - Tarde', 1, 'custom', NOW()),
(616, @ptbr, 'Especifique a hora', 1, 'custom', NOW()),
(617, @ptbr, 'Válido a partir de', 1, 'custom', NOW()),
(618, @ptbr, 'Válido para', 1, 'custom', NOW()),
(619, @ptbr, 'Os direitos não serão excluídos, pois já estão em uso', 1, 'custom', NOW()),
(620, @ptbr, 'Número de dias', 1, 'custom', NOW()),
(621, @ptbr, 'F?rias saldo (dias)', 1, 'custom', NOW()),
(622, @ptbr, 'Ver detalhes da licença', 1, 'custom', NOW()),
(623, @ptbr, 'Ver informações doPIM', 1, 'custom', NOW()),
(624, @ptbr, 'Cancelar licença', 1, 'custom', NOW()),
(626, @ptbr, '{ação, selecione,APPROVE{Approve Leave}REJECT{Reject Leave}outro{Cancel Leave}}', 1, 'custom', NOW()),
(627, @ptbr, 'Falha ao enviar', 1, 'custom', NOW()),
(628, @ptbr, 'Falha ao enviar: nenhum dia útil selecionado', 1, 'custom', NOW()),
(629, @ptbr, '{contagem, plural, =0{No Entitlement added}um{Entitlement added to 1 employee}outro{Entitlement added to # employees}}', 1, 'custom', NOW()),
(630, @ptbr, 'Meio dia', 1, 'custom', NOW()),
(631, @ptbr, 'Dia não útil', 1, 'custom', NOW()),
(632, @ptbr, 'Rejeitado', 1, 'custom', NOW()),
(633, @ptbr, 'Cancelado', 1, 'custom', NOW()),
(634, @ptbr, 'Direitos de licença (dias)', 1, 'custom', NOW()),
(635, @ptbr, 'F?rias aprovação pendente (dias)', 1, 'custom', NOW()),
(636, @ptbr, 'Sair agendado (dias)', 1, 'custom', NOW()),
(637, @ptbr, 'Licença tirada (dias)', 1, 'custom', NOW()),
(638, @ptbr, 'Licença solicitada para', 1, 'custom', NOW()),
(639, @ptbr, 'Todos os dias', 1, 'custom', NOW()),
(640, @ptbr, 'Apenas no dia de início', 1, 'custom', NOW()),
(641, @ptbr, 'Fim do dia apenas', 1, 'custom', NOW()),
(642, @ptbr, 'Dia de início e término', 1, 'custom', NOW()),
(643, @ptbr, 'Atividades', 1, 'custom', NOW()),
(644, @ptbr, 'Copiar de', 1, 'custom', NOW()),
(645, @ptbr, 'Nome da atividade', 1, 'custom', NOW()),
(646, @ptbr, 'Não é permitido excluir atividades do projeto que tenham tempo registrado', 1, 'custom', NOW()),
(647, @ptbr, 'Adicionar cliente', 1, 'custom', NOW()),
(648, @ptbr, 'Adicionar quadro de horários', 1, 'custom', NOW()),
(649, @ptbr, 'Selecione um dia para criar o quadro de horários', 1, 'custom', NOW()),
(650, @ptbr, 'Atividade de cópia', 1, 'custom', NOW()),
(651, @ptbr, 'Nome do Projeto', 1, 'custom', NOW()),
(652, @ptbr, 'Nenhuma atividade atribuída', 1, 'custom', NOW()),
(653, @ptbr, 'Nenhuma atividade selecionada', 1, 'custom', NOW()),
(654, @ptbr, 'Nome do cliente', 1, 'custom', NOW()),
(655, @ptbr, 'Editar atividade do projeto', 1, 'custom', NOW()),
(656, @ptbr, 'Administrador do projeto', 1, 'custom', NOW()),
(657, @ptbr, 'Projeto', 1, 'custom', NOW()),
(658, @ptbr, 'Adicionar atividade de projeto', 1, 'custom', NOW()),
(659, @ptbr, 'Ação do quadro de horários', 1, 'custom', NOW()),
(660, @ptbr, 'Nenhum quadro de horários encontrado', 1, 'custom', NOW()),
(661, @ptbr, 'Atividade', 1, 'custom', NOW()),
(662, @ptbr, 'Adicionar linha', 1, 'custom', NOW()),
(663, @ptbr, 'Selecione um projeto', 1, 'custom', NOW()),
(664, @ptbr, 'Selecione uma atividade', 1, 'custom', NOW()),
(665, @ptbr, 'Registro duplicado', 1, 'custom', NOW()),
(666, @ptbr, 'Selecione um projeto e uma atividade', 1, 'custom', NOW()),
(667, @ptbr, 'Deve ser menor que 24 e estar emHH:MMou formato decimal', 1, 'custom', NOW()),
(668, @ptbr, 'O total deve ser inferior a 24 horas', 1, 'custom', NOW()),
(669, @ptbr, 'Ações realizadas no quadro de horários', 1, 'custom', NOW()),
(670, @ptbr, 'Quadros de horários com ação pendente', 1, 'custom', NOW()),
(671, @ptbr, 'Período do quadro de horários', 1, 'custom', NOW()),
(672, @ptbr, 'Definir período do quadro de horários', 1, 'custom', NOW()),
(673, @ptbr, 'Primeiro dia da semana', 1, 'custom', NOW()),
(674, @ptbr, 'Não é permitido excluir clientes associados a projetos que tenham horas registradas neles', 1, 'custom', NOW()),
(675, @ptbr, 'Editar cliente', 1, 'custom', NOW()),
(676, @ptbr, 'Administradores de projeto', 1, 'custom', NOW()),
(677, @ptbr, 'Não é permitido excluir projetos que tenham tempo registrado neles', 1, 'custom', NOW()),
(678, @ptbr, 'Editar projeto', 1, 'custom', NOW()),
(679, @ptbr, 'Relatório do Projeto', 1, 'custom', NOW()),
(680, @ptbr, 'Intervalo de datas do projeto', 1, 'custom', NOW()),
(681, @ptbr, 'Incluir apenas planilhas de horas aprovadas', 1, 'custom', NOW()),
(682, @ptbr, 'Duração total (horas)', 1, 'custom', NOW()),
(683, @ptbr, 'Relatório de funcionários', 1, 'custom', NOW()),
(684, @ptbr, 'Selecione Funcionário', 1, 'custom', NOW()),
(685, @ptbr, 'O dia de início do período do quadro de horários não foi definido. Entre em contato com o administradorHR', 1, 'custom', NOW()),
(686, @ptbr, 'Meu quadro de horários', 1, 'custom', NOW()),
(687, @ptbr, 'Editar quadro de horários', 1, 'custom', NOW()),
(688, @ptbr, 'Criar quadro de horários', 1, 'custom', NOW()),
(689, @ptbr, 'Quadro de horários para', 1, 'custom', NOW()),
(690, @ptbr, 'Editar quadro de horários para', 1, 'custom', NOW()),
(691, @ptbr, 'Adicionar projeto', 1, 'custom', NOW()),
(692, @ptbr, 'Quadro de horários criado com sucesso', 1, 'custom', NOW()),
(693, @ptbr, 'Quadro de horários rejeitado', 1, 'custom', NOW()),
(694, @ptbr, 'Quadro de horários aprovado', 1, 'custom', NOW()),
(695, @ptbr, 'Redefinição do quadro de horários', 1, 'custom', NOW()),
(696, @ptbr, 'O horário de punch out deve ser posterior ao punch in time', 1, 'custom', NOW()),
(697, @ptbr, 'Ponto (horas)', 1, 'custom', NOW()),
(698, @ptbr, 'Quadro de horários enviado', 1, 'custom', NOW()),
(699, @ptbr, 'Registrado a tempo', 1, 'custom', NOW()),
(700, @ptbr, 'Configuração de presença', 1, 'custom', NOW()),
(701, @ptbr, 'O funcionário pode alterar a hora atual ao marcar entrada/saída', 1, 'custom', NOW()),
(702, @ptbr, 'O funcionário pode editar/excluir seus próprios registros de presença', 1, 'custom', NOW()),
(703, @ptbr, 'O supervisor pode adicionar/editar/excluir registros de presença de subordinados', 1, 'custom', NOW()),
(704, @ptbr, 'Relatório resumido do total de presenças', 1, 'custom', NOW()),
(705, @ptbr, 'Editar registros de presença', 1, 'custom', NOW()),
(706, @ptbr, 'Registrar entrada', 1, 'custom', NOW()),
(707, @ptbr, 'hh: mm', 1, 'custom', NOW()),
(708, @ptbr, 'Registrar sa?da', 1, 'custom', NOW()),
(709, @ptbr, 'Registros sobrepostos encontrados', 1, 'custom', NOW()),
(710, @ptbr, 'Nota de perfuração', 1, 'custom', NOW()),
(711, @ptbr, 'Nota perfurada', 1, 'custom', NOW()),
(712, @ptbr, 'Duração (horas)', 1, 'custom', NOW()),
(713, @ptbr, 'Registros de frequ?ncia do colaborador', 1, 'custom', NOW()),
(714, @ptbr, 'Meus registros de presença', 1, 'custom', NOW()),
(715, @ptbr, 'Fuso horário', 1, 'custom', NOW()),
(716, @ptbr, 'Nota perfurada', 1, 'custom', NOW()),
(717, @ptbr, 'Em', 1, 'custom', NOW()),
(718, @ptbr, 'Fora', 1, 'custom', NOW()),
(719, @ptbr, 'Limpar registros de funcionários', 1, 'custom', NOW()),
(720, @ptbr, '(Colaborador antigo)', 1, 'custom', NOW()),
(721, @ptbr, 'Os usuários que desejam acessar seus dados, ou que desejam corrigir, alterar ou excluir as informações fornecidas devem direcionar suas solicitações para Data@orangehrm.com com o assunto "Purge Records (Instance Identifier:{instanceIdentifier})"', 1, 'custom', NOW()),
(722, @ptbr, 'Purga', 1, 'custom', NOW()),
(723, @ptbr, 'Expurgar funcionário', 1, 'custom', NOW()),
(724, @ptbr, 'Você está prestes a expurgar o funcionário permanentemente. Tem certeza de que deseja continuar? Esta operação não pode ser desfeita', 1, 'custom', NOW()),
(725, @ptbr, 'Sim, purgar', 1, 'custom', NOW()),
(726, @ptbr, 'Funcionário Selecionado', 1, 'custom', NOW()),
(727, @ptbr, 'Purgado com sucesso', 1, 'custom', NOW()),
(728, @ptbr, 'Baixar dados pessoais', 1, 'custom', NOW()),
(730, @ptbr, 'Suporte ao Cliente', 1, 'custom', NOW()),
(731, @ptbr, 'Aprender como usar um novo aplicativo pode ser um desafio. Na OrangeHRM, temos o compromisso de fornecer a você o conhecimento e as habilidades necessárias para utilizar totalmente o aplicativo, permitindo que você gerencie seus processosHRde forma rápida e eficiente.', 1, 'custom', NOW()),
(732, @ptbr, 'Os seguintes repositórios de informações estão disponíveis para ajudá-lo a entender o aplicativo:', 1, 'custom', NOW()),
(733, @ptbr, 'Se você tiver algum problema, não hesite em nos contatar em', 1, 'custom', NOW()),
(734, @ptbr, 'Teremos o maior prazer em ajudar.', 1, 'custom', NOW()),
(735, @ptbr, 'Entrar', 1, 'custom', NOW()),
(736, @ptbr, 'Usu?rio', 1, 'custom', NOW()),
(737, @ptbr, 'Senha', 1, 'custom', NOW()),
(738, @ptbr, 'Credencial necessária', 1, 'custom', NOW()),
(739, @ptbr, 'Acesso de Administrador', 1, 'custom', NOW()),
(740, @ptbr, 'Você solicitou acesso a uma função crítica de administrador no OrangeHRM e deve validar suas credenciais abaixo', 1, 'custom', NOW()),
(744, @ptbr, 'Redefinir senha', 1, 'custom', NOW()),
(745, @ptbr, 'Por favor, digite seu nome de usuário para identificar sua conta e redefinir sua senha', 1, 'custom', NOW()),
(746, @ptbr, 'Defina uma nova senha', 1, 'custom', NOW()),
(747, @ptbr, 'Nova senha', 1, 'custom', NOW()),
(748, @ptbr, 'A conta do usuário não pode ser encontrada ou o token de redefinição de senha expirou', 1, 'custom', NOW()),
(749, @ptbr, 'para solicitar um novo token de redefinição de senha', 1, 'custom', NOW()),
(750, @ptbr, 'Link de redefinição de senha enviado com sucesso', 1, 'custom', NOW()),
(751, @ptbr, 'O sistema OrangeHRM não está configurado para receber notificações por email. Entre em contato com o administrador do OrangeHRM para redefinir sua senha', 1, 'custom', NOW()),
(752, @ptbr, 'para voltar à página de login', 1, 'custom', NOW()),
(753, @ptbr, 'Um link de redefinição de senha foi enviado a você por e-mail.', 1, 'custom', NOW()),
(754, @ptbr, 'Você pode seguir esse link e selecionar uma nova senha.', 1, 'custom', NOW()),
(755, @ptbr, 'Se o e-mail não chegar, entre em contato com o administrador do OrangeHRM.', 1, 'custom', NOW()),
(756, @ptbr, 'Esqueci sua senha', 1, 'custom', NOW()),
(757, @ptbr, 'Credenciais inválidas', 1, 'custom', NOW()),
(758, @ptbr, 'Falha na validação do tokenCSRF', 1, 'custom', NOW()),
(759, @ptbr, 'Conta desativada', 1, 'custom', NOW()),
(760, @ptbr, 'Funcionário é demitido', 1, 'custom', NOW()),
(761, @ptbr, 'Funcionário não atribuído', 1, 'custom', NOW()),
(762, @ptbr, 'Ver histórico de ações', 1, 'custom', NOW()),
(763, @ptbr, 'Entrevistador', 1, 'custom', NOW()),
(764, @ptbr, 'Título da Entrevista', 1, 'custom', NOW()),
(765, @ptbr, 'Agendar Entrevista', 1, 'custom', NOW()),
(766, @ptbr, 'Lista', 1, 'custom', NOW()),
(767, @ptbr, 'Status atual', 1, 'custom', NOW()),
(768, @ptbr, 'Ação Realizada', 1, 'custom', NOW()),
(769, @ptbr, 'Data de realização', 1, 'custom', NOW()),
(770, @ptbr, 'Vaga', 1, 'custom', NOW()),
(771, @ptbr, 'Gerente de contratação', 1, 'custom', NOW()),
(772, @ptbr, 'Nome do Candidato', 1, 'custom', NOW()),
(773, @ptbr, 'Palavras-chave', 1, 'custom', NOW()),
(774, @ptbr, 'Data da aplicação', 1, 'custom', NOW()),
(775, @ptbr, 'Método de Aplicação', 1, 'custom', NOW()),
(776, @ptbr, 'Insira palavras separadas por vírgula', 1, 'custom', NOW()),
(777, @ptbr, 'Candidato', 1, 'custom', NOW()),
(778, @ptbr, 'Aplicativo iniciado', 1, 'custom', NOW()),
(779, @ptbr, 'Selecionado', 1, 'custom', NOW()),
(780, @ptbr, 'Entrevista agendada', 1, 'custom', NOW()),
(781, @ptbr, 'Entrevista aprovada', 1, 'custom', NOW()),
(782, @ptbr, 'Falha na entrevista', 1, 'custom', NOW()),
(783, @ptbr, 'Emprego oferecido', 1, 'custom', NOW()),
(784, @ptbr, 'Oferta recusada', 1, 'custom', NOW()),
(785, @ptbr, 'Manual', 1, 'custom', NOW()),
(786, @ptbr, 'On-line', 1, 'custom', NOW()),
(787, @ptbr, 'Número de contato', 1, 'custom', NOW()),
(788, @ptbr, 'Consentimento para manter dados', 1, 'custom', NOW()),
(789, @ptbr, 'Retomar', 1, 'custom', NOW()),
(790, @ptbr, 'Adicionar candidato', 1, 'custom', NOW()),
(791, @ptbr, 'Deve ser a data atual ou uma data anterior', 1, 'custom', NOW()),
(792, @ptbr, 'Estágio de Aplicação', 1, 'custom', NOW()),
(793, @ptbr, 'Oferecer emprego', 1, 'custom', NOW()),
(794, @ptbr, 'Marcar entrevista falhou', 1, 'custom', NOW()),
(795, @ptbr, 'Marcar entrevista aprovada', 1, 'custom', NOW()),
(796, @ptbr, 'Recusar oferta', 1, 'custom', NOW()),
(797, @ptbr, 'Contratar', 1, 'custom', NOW()),
(799, @ptbr, 'Vaga de Emprego', 1, 'custom', NOW()),
(801, @ptbr, 'Perfil do Candidato', 1, 'custom', NOW()),
(802, @ptbr, 'Histórico do Candidato', 1, 'custom', NOW()),
(803, @ptbr, 'Adicionar vaga', 1, 'custom', NOW()),
(804, @ptbr, 'Editar vaga', 1, 'custom', NOW()),
(805, @ptbr, 'Nome da vaga', 1, 'custom', NOW()),
(806, @ptbr, 'Número de posições', 1, 'custom', NOW()),
(807, @ptbr, 'RSSAlimentaçãoURL', 1, 'custom', NOW()),
(808, @ptbr, 'Página da WebURL', 1, 'custom', NOW()),
(809, @ptbr, 'Publicar no feedRSSe na página da web', 1, 'custom', NOW()),
(810, @ptbr, '{employee}adicionou{candidate}', 1, 'custom', NOW()),
(811, @ptbr, '{employee}atribuiu a vaga de emprego{vacancy}', 1, 'custom', NOW()),
(812, @ptbr, 'Selecionado para{vacancy}por{employee}', 1, 'custom', NOW()),
(813, @ptbr, '{employee}programou{interview}em{interviewDate}com{interviewers}para{vacancy}', 1, 'custom', NOW()),
(814, @ptbr, '{employee}marcou{interview}como aprovado para{vacancy}', 1, 'custom', NOW()),
(815, @ptbr, '{employee}marcou{interview}como falhou para{vacancy}', 1, 'custom', NOW()),
(816, @ptbr, '{employee}ofereceu o emprego para{vacancy}', 1, 'custom', NOW()),
(817, @ptbr, '{employee}marcou a oferta como recusada para{vacancy}', 1, 'custom', NOW()),
(818, @ptbr, '{employee}contratou{candidate}para{vacancy}', 1, 'custom', NOW()),
(819, @ptbr, '{employee}rejeitou{candidate}do{vacancy}', 1, 'custom', NOW()),
(820, @ptbr, '{employee}removeu{candidate}do{vacancy}', 1, 'custom', NOW()),
(821, @ptbr, '{candidate}se candidatou à vaga{vacancy}', 1, 'custom', NOW()),
(822, @ptbr, 'Candidato da lista restrita', 1, 'custom', NOW()),
(823, @ptbr, 'Contratado', 1, 'custom', NOW()),
(824, @ptbr, 'Distribuído por', 1, 'custom', NOW()),
(825, @ptbr, 'Inscreva-se para{vacancyName}', 1, 'custom', NOW()),
(826, @ptbr, 'Solicitação recebida', 1, 'custom', NOW()),
(827, @ptbr, 'Sua inscrição foi enviada com sucesso', 1, 'custom', NOW()),
(828, @ptbr, 'Contratar Candidato', 1, 'custom', NOW()),
(829, @ptbr, 'Rejeitar candidato', 1, 'custom', NOW()),
(830, @ptbr, 'Esta ação removerá a vaga anterior. Tem certeza de que deseja continuar?', 1, 'custom', NOW()),
(831, @ptbr, 'Revisor Supervisor', 1, 'custom', NOW()),
(832, @ptbr, 'Adicionar avaliação', 1, 'custom', NOW()),
(833, @ptbr, 'Data de início do período de revisão', 1, 'custom', NOW()),
(834, @ptbr, 'Data de término do período de revisão', 1, 'custom', NOW()),
(835, @ptbr, 'Data de vencimento', 1, 'custom', NOW()),
(836, @ptbr, 'Ativar', 1, 'custom', NOW()),
(837, @ptbr, 'A data de início do período de revisão deve ser anterior à data de término do período', 1, 'custom', NOW()),
(838, @ptbr, 'A data de término do período de revisão deve ser posterior à data de início do período', 1, 'custom', NOW()),
(839, @ptbr, 'A data de vencimento deve ser posterior à data de término do período', 1, 'custom', NOW()),
(840, @ptbr, 'Não é possível ativar a revisão para funcionários que não possuem Cargo e/ou Subdivisão', 1, 'custom', NOW()),
(841, @ptbr, 'Não é possível ativar a revisão sem KPIs', 1, 'custom', NOW()),
(842, @ptbr, 'Revisores', 1, 'custom', NOW()),
(843, @ptbr, 'Nome do rastreador', 1, 'custom', NOW()),
(844, @ptbr, 'Editar rastreador de desempenho', 1, 'custom', NOW()),
(845, @ptbr, 'Adicionar rastreador de desempenho', 1, 'custom', NOW()),
(846, @ptbr, 'O funcionário não pode ser designado como seu próprio revisor', 1, 'custom', NOW()),
(847, @ptbr, 'Rastreadores de desempenho', 1, 'custom', NOW()),
(848, @ptbr, 'Principais indicadores de desempenho para cargo', 1, 'custom', NOW()),
(849, @ptbr, 'Indicador-chave de desempenho', 1, 'custom', NOW()),
(850, @ptbr, 'Taxa mínima', 1, 'custom', NOW()),
(851, @ptbr, 'Taxa máxima', 1, 'custom', NOW()),
(852, @ptbr, 'É padrão', 1, 'custom', NOW()),
(853, @ptbr, 'Adicionar indicador-chave de desempenho', 1, 'custom', NOW()),
(854, @ptbr, 'Editar indicador-chave de desempenho', 1, 'custom', NOW()),
(855, @ptbr, 'Classificação Mínima', 1, 'custom', NOW()),
(856, @ptbr, 'Classificação Máxima', 1, 'custom', NOW()),
(857, @ptbr, 'Tornar escala padrão', 1, 'custom', NOW()),
(858, @ptbr, 'A classificação mínima deve ser inferior à classificação máxima', 1, 'custom', NOW()),
(859, @ptbr, 'A classificação máxima deve ser maior que a classificação mínima', 1, 'custom', NOW()),
(860, @ptbr, 'Rastreadores de desempenho de funcionários', 1, 'custom', NOW()),
(861, @ptbr, 'Data de modificação', 1, 'custom', NOW()),
(862, @ptbr, 'Data adicionada', 1, 'custom', NOW()),
(863, @ptbr, 'Rastreador', 1, 'custom', NOW()),
(864, @ptbr, 'Meus rastreadores de desempenho', 1, 'custom', NOW()),
(865, @ptbr, 'Período de revisão', 1, 'custom', NOW()),
(866, @ptbr, 'Status de autoavaliação', 1, 'custom', NOW()),
(867, @ptbr, 'Rever estado', 1, 'custom', NOW()),
(868, @ptbr, 'Avaliar', 1, 'custom', NOW()),
(869, @ptbr, 'Avalia??es de colaboradores', 1, 'custom', NOW()),
(870, @ptbr, 'Ativado', 1, 'custom', NOW()),
(871, @ptbr, 'Em andamento', 1, 'custom', NOW()),
(872, @ptbr, 'Concluído', 1, 'custom', NOW()),
(873, @ptbr, 'Revisor', 1, 'custom', NOW()),
(874, @ptbr, 'Gerenciar avaliações de desempenho', 1, 'custom', NOW()),
(875, @ptbr, 'Inativo', 1, 'custom', NOW()),
(876, @ptbr, 'Registros do rastreador', 1, 'custom', NOW()),
(877, @ptbr, 'Adicionar registro', 1, 'custom', NOW()),
(878, @ptbr, 'Adicionado', 1, 'custom', NOW()),
(879, @ptbr, 'Modificado em', 1, 'custom', NOW()),
(880, @ptbr, 'Excluir', 1, 'custom', NOW()),
(881, @ptbr, 'Adicionar registro do rastreador', 1, 'custom', NOW()),
(882, @ptbr, 'Registro', 1, 'custom', NOW()),
(883, @ptbr, 'Positivo', 1, 'custom', NOW()),
(884, @ptbr, 'Negativo', 1, 'custom', NOW()),
(885, @ptbr, 'Editar registro do rastreador', 1, 'custom', NOW()),
(886, @ptbr, 'Avaliação de desempenho', 1, 'custom', NOW()),
(887, @ptbr, 'Resumo da revisão', 1, 'custom', NOW()),
(888, @ptbr, 'Revise a data de vencimento', 1, 'custom', NOW()),
(889, @ptbr, 'Completo', 1, 'custom', NOW()),
(890, @ptbr, 'Finalização da revisão', 1, 'custom', NOW()),
(891, @ptbr, 'Data de conclusão', 1, 'custom', NOW()),
(892, @ptbr, 'Avaliação final', 1, 'custom', NOW()),
(893, @ptbr, 'Comentários Finais', 1, 'custom', NOW()),
(894, @ptbr, 'A classificação deve ser maior ou igual a{minValue}', 1, 'custom', NOW()),
(895, @ptbr, 'A classificação deve ser menor ou igual a{maxValue}', 1, 'custom', NOW()),
(896, @ptbr, 'Autoavaliação por', 1, 'custom', NOW()),
(897, @ptbr, 'Avaliação do Supervisor por', 1, 'custom', NOW()),
(898, @ptbr, 'KPI', 1, 'custom', NOW()),
(899, @ptbr, 'Avaliação', 1, 'custom', NOW()),
(900, @ptbr, 'Mínimo', 1, 'custom', NOW()),
(901, @ptbr, 'Máx.', 1, 'custom', NOW()),
(902, @ptbr, 'Avaliação ativada', 1, 'custom', NOW()),
(903, @ptbr, 'Avaliação em andamento', 1, 'custom', NOW()),
(904, @ptbr, 'Avaliação concluída', 1, 'custom', NOW()),
(905, @ptbr, 'Não é possível ativar a revisão para funcionários que não possuem cargo comKPI', 1, 'custom', NOW()),
(906, @ptbr, 'Não é possível adicionar um ex-funcionário como revisor', 1, 'custom', NOW()),
(907, @ptbr, 'O supervisor selecionado para o revisor é inválido', 1, 'custom', NOW()),
(908, @ptbr, 'Comentário Geral', 1, 'custom', NOW()),
(909, @ptbr, 'Confirmar envio de revisão', 1, 'custom', NOW()),
(910, @ptbr, 'A revisão será feita somente leitura após a conclusão. Esta ação não pode ser desfeita. Tem certeza de que deseja continuar?', 1, 'custom', NOW()),
(911, @ptbr, 'Não é possível adicionar um ex-funcionário como revisor', 1, 'custom', NOW()),
(912, @ptbr, 'Editar revisão', 1, 'custom', NOW()),
(913, @ptbr, 'Cor Primária', 1, 'custom', NOW()),
(914, @ptbr, 'Cor Secundária', 1, 'custom', NOW()),
(915, @ptbr, 'Cor da fonte primária', 1, 'custom', NOW()),
(916, @ptbr, 'Cor da fonte secundária', 1, 'custom', NOW()),
(917, @ptbr, 'Cor gradiente primária 1', 1, 'custom', NOW()),
(918, @ptbr, 'Cor gradiente primária 2', 1, 'custom', NOW()),
(919, @ptbr, 'Logotipo do cliente', 1, 'custom', NOW()),
(920, @ptbr, 'Banner do cliente', 1, 'custom', NOW()),
(921, @ptbr, 'Banner de login', 1, 'custom', NOW()),
(922, @ptbr, 'Imagens de mídia social', 1, 'custom', NOW()),
(923, @ptbr, 'Exportar', 1, 'custom', NOW()),
(924, @ptbr, 'Traduzir', 1, 'custom', NOW()),
(926, @ptbr, 'Adicionar pacote de idiomas', 1, 'custom', NOW()),
(927, @ptbr, 'Módulo de diretório', 1, 'custom', NOW()),
(928, @ptbr, 'Janeiro', 1, 'custom', NOW()),
(929, @ptbr, 'Fevereiro', 1, 'custom', NOW()),
(930, @ptbr, 'Mar?o', 1, 'custom', NOW()),
(931, @ptbr, 'Abril', 1, 'custom', NOW()),
(932, @ptbr, 'Mai', 1, 'custom', NOW()),
(933, @ptbr, 'Junho', 1, 'custom', NOW()),
(934, @ptbr, 'Julho', 1, 'custom', NOW()),
(935, @ptbr, 'Agosto', 1, 'custom', NOW()),
(936, @ptbr, 'Setembro', 1, 'custom', NOW()),
(937, @ptbr, 'Outubro', 1, 'custom', NOW()),
(938, @ptbr, 'Novembro', 1, 'custom', NOW()),
(939, @ptbr, 'Dezembro', 1, 'custom', NOW()),
(940, @ptbr, 'Jan', 1, 'custom', NOW()),
(941, @ptbr, 'Fev', 1, 'custom', NOW()),
(942, @ptbr, 'Mar', 1, 'custom', NOW()),
(943, @ptbr, 'Abr', 1, 'custom', NOW()),
(944, @ptbr, 'Jun', 1, 'custom', NOW()),
(945, @ptbr, 'Jul', 1, 'custom', NOW()),
(946, @ptbr, 'Ago', 1, 'custom', NOW()),
(947, @ptbr, 'Set', 1, 'custom', NOW()),
(948, @ptbr, 'Out', 1, 'custom', NOW()),
(949, @ptbr, 'Nov', 1, 'custom', NOW()),
(950, @ptbr, 'Dez', 1, 'custom', NOW()),
(952, @ptbr, 'Deve ser inferior ao valor máximo', 1, 'custom', NOW()),
(953, @ptbr, 'Deve ser um número entre{min}-{max}', 1, 'custom', NOW()),
(954, @ptbr, 'Ativo', 1, 'custom', NOW()),
(955, @ptbr, 'Fechado', 1, 'custom', NOW()),
(956, @ptbr, 'Tamanho do arquivo', 1, 'custom', NOW()),
(957, @ptbr, 'Tipo de arquivo', 1, 'custom', NOW()),
(958, @ptbr, 'Nome completo', 1, 'custom', NOW()),
(959, @ptbr, 'Redefinir para o padrão', 1, 'custom', NOW()),
(960, @ptbr, 'Visualização', 1, 'custom', NOW()),
(961, @ptbr, 'Aceita jpg, .png, .gif, .svg até{fileSize}. Dimensões recomendadas:{width}px X{height}px', 1, 'custom', NOW()),
(962, @ptbr, 'Dimensões incorretas', 1, 'custom', NOW()),
(963, @ptbr, 'Inv?lido', 1, 'custom', NOW()),
(964, @ptbr, 'Ou faça login com', 1, 'custom', NOW()),
(965, @ptbr, 'Ativado com sucesso', 1, 'custom', NOW()),
(966, @ptbr, 'Publicar', 1, 'custom', NOW()),
(967, @ptbr, 'O número deve ser menor ou igual a{maxValue}', 1, 'custom', NOW()),
(968, @ptbr, 'O número deve ser maior ou igual a{minValue}', 1, 'custom', NOW()),
(969, @ptbr, 'Funcionário expurgado', 1, 'custom', NOW()),
(970, @ptbr, 'Mostrar mais', 1, 'custom', NOW()),
(971, @ptbr, 'Mostrar menos', 1, 'custom', NOW()),
(972, @ptbr, 'Carregar{fileName}', 1, 'custom', NOW()),
(974, @ptbr, 'Deve ser um valor numérico', 1, 'custom', NOW()),
(975, @ptbr, 'Confirmação necessária', 1, 'custom', NOW()),
(976, @ptbr, 'Eliminar registros de candidatos', 1, 'custom', NOW()),
(977, @ptbr, 'Expurgar Candidatos', 1, 'custom', NOW()),
(978, @ptbr, 'Você está prestes a eliminar permanentemente os candidatos selecionados. Tem certeza de que deseja continuar? Esta operação não pode ser desfeita', 1, 'custom', NOW()),
(979, @ptbr, 'Limpar tudo', 1, 'custom', NOW()),
(981, @ptbr, 'Pacote de idiomas', 1, 'custom', NOW()),
(982, @ptbr, 'Idioma de origem', 1, 'custom', NOW()),
(983, @ptbr, 'Módulo', 1, 'custom', NOW()),
(984, @ptbr, 'Texto Fonte', 1, 'custom', NOW()),
(985, @ptbr, 'Texto traduzido', 1, 'custom', NOW()),
(986, @ptbr, 'Nota de origem', 1, 'custom', NOW()),
(987, @ptbr, 'Mostrar', 1, 'custom', NOW()),
(988, @ptbr, 'Todos', 1, 'custom', NOW()),
(989, @ptbr, 'Traduzido', 1, 'custom', NOW()),
(990, @ptbr, 'Não traduzido', 1, 'custom', NOW()),
(991, @ptbr, 'Traduzir pacote de idiomas', 1, 'custom', NOW()),
(992, @ptbr, 'Ordem', 1, 'custom', NOW()),
(993, @ptbr, 'Configurações do servidor', 1, 'custom', NOW()),
(994, @ptbr, 'Configurações de vinculação', 1, 'custom', NOW()),
(995, @ptbr, 'Configurações de pesquisa de usuário', 1, 'custom', NOW()),
(996, @ptbr, 'Mapeamento de dados', 1, 'custom', NOW()),
(997, @ptbr, 'Configurações adicionais', 1, 'custom', NOW()),
(998, @ptbr, 'Hospedar', 1, 'custom', NOW()),
(999, @ptbr, 'LDAPServidorIPou Hostname sem o protocolo (sem ldap:// ou ldaps://)', 1, 'custom', NOW()),
(1000, @ptbr, 'Porta', 1, 'custom', NOW()),
(1001, @ptbr, 'SeSSLusar a porta 636 por padrão', 1, 'custom', NOW()),
(1002, @ptbr, 'Criptografia', 1, 'custom', NOW()),
(1003, @ptbr, 'ImplementaçãoLDAP', 1, 'custom', NOW()),
(1004, @ptbr, 'Nome Distinto', 1, 'custom', NOW()),
(1005, @ptbr, 'Nome Distinto Base', 1, 'custom', NOW()),
(1006, @ptbr, 'Escopo da pesquisa', 1, 'custom', NOW()),
(1007, @ptbr, 'A opção de subárvore permitirá pesquisar o diretório base e subdiretórios. Um nível pesquisará apenas no diretório base', 1, 'custom', NOW()),
(1008, @ptbr, 'Atributo de nome de usuário', 1, 'custom', NOW()),
(1015, @ptbr, 'Conexão de teste', 1, 'custom', NOW()),
(1016, @ptbr, 'Vincular anonimamente', 1, 'custom', NOW()),
(1017, @ptbr, 'Intervalo de sincronização (em horas)', 1, 'custom', NOW()),
(1023, @ptbr, 'Campo de atributo a ser usado ao carregar o nome de usuário. Ex: cn, nome da contaSMA', 1, 'custom', NOW()),
(1024, @ptbr, 'SSL', 1, 'custom', NOW()),
(1025, @ptbr, 'Subárvore', 1, 'custom', NOW()),
(1026, @ptbr, 'Um nível', 1, 'custom', NOW()),
(1027, @ptbr, 'AbraLDAPv3', 1, 'custom', NOW()),
(1028, @ptbr, 'Diretório ativoMS', 1, 'custom', NOW()),
(1029, @ptbr, 'Status da conexão', 1, 'custom', NOW()),
(1030, @ptbr, 'Sincronizar conexão', 1, 'custom', NOW()),
(1031, @ptbr, 'Sincronizar agora', 1, 'custom', NOW()),
(1032, @ptbr, 'Última sincronização em{datetime}', 1, 'custom', NOW()),
(1033, @ptbr, 'A última sincronização falhou em{datetime}', 1, 'custom', NOW()),
(1034, @ptbr, 'Sincronização bem-sucedida', 1, 'custom', NOW()),
(1035, @ptbr, 'Falha na sincronização', 1, 'custom', NOW()),
(1036, @ptbr, 'Filtro de pesquisa de usuário', 1, 'custom', NOW()),
(1037, @ptbr, 'AtributoIDexclusivo do usuário', 1, 'custom', NOW()),
(1038, @ptbr, 'Mesclar usuáriosLDAPcom usuários de sistema existentes', 1, 'custom', NOW()),
(1039, @ptbr, 'Por favor, verifique as configurações da sua configuraçãoLDAP', 1, 'custom', NOW()),
(1040, @ptbr, 'Campo de atributo a ser usado ao pesquisar objetos de usuário. Ex: objectClass=pessoa', 1, 'custom', NOW()),
(1041, @ptbr, 'Campo de atributo a ser usado como um identificador imutável exclusivo para objetos de usuário. Isso é usado para rastrear alterações de nome de usuário. Ex: entradaUUID, objectGUID', 1, 'custom', NOW()),
(1042, @ptbr, 'Campo em OrangeHRM', 1, 'custom', NOW()),
(1043, @ptbr, 'Campo no diretórioLDAP', 1, 'custom', NOW()),
(1044, @ptbr, 'Use este campo como campo de mapeamento de funcionário/usuário', 1, 'custom', NOW()),
(1045, @ptbr, 'Usuário(s){count}encontrados', 1, 'custom', NOW()),
(1046, @ptbr, 'Usuários{count}serão importados', 1, 'custom', NOW()),
(1047, @ptbr, 'Pesquisa', 1, 'custom', NOW()),
(1048, @ptbr, 'Pesquisa de usuário', 1, 'custom', NOW()),
(1049, @ptbr, 'Autenticação', 1, 'custom', NOW()),
(1050, @ptbr, 'Resultados da pesquisa', 1, 'custom', NOW()),
(1051, @ptbr, 'Sair dos aplicativos', 1, 'custom', NOW()),
(1052, @ptbr, 'Sair das atribuições', 1, 'custom', NOW()),
(1053, @ptbr, 'F?rias aprovações', 1, 'custom', NOW()),
(1054, @ptbr, 'F?rias cancelamentos', 1, 'custom', NOW()),
(1055, @ptbr, 'F?rias rejeições', 1, 'custom', NOW()),
(1056, @ptbr, 'ConfiguraçõesLDAPnão configuradas', 1, 'custom', NOW()),
(1057, @ptbr, 'SincronizaçãoLDAPnão habilitada', 1, 'custom', NOW()),
(1058, @ptbr, 'Antes de ativar o serviçoLDAP, certifique-se de que todas as configurações doLDAPestejam funcionando corretamente, pois a configuração incorreta pode resultar em dados corrompidos. Como precaução, recomendamos que você crie um backup do seu banco de dados antes de continuar.', 1, 'custom', NOW()),
(1059, @ptbr, 'Ascendente', 1, 'custom', NOW()),
(1060, @ptbr, 'Descendente', 1, 'custom', NOW()),
(1061, @ptbr, 'ConfiguraçãoLDAP', 1, 'custom', NOW()),
(1062, @ptbr, 'Habilitar', 1, 'custom', NOW()),
(1063, @ptbr, 'Insira um número de porta válido entre{minValue}e{maxValue}', 1, 'custom', NOW()),
(1064, @ptbr, 'Status do usuário', 1, 'custom', NOW()),
(1065, @ptbr, 'Deve ter pelo menos caracteres{amount}', 1, 'custom', NOW()),
(1066, @ptbr, 'Tipo de direito', 1, 'custom', NOW()),
(1067, @ptbr, '{ação, seleção,APPROVE{{contagem, plural, =0{No Leave Requests Approved}=1{1 Leave Request Approved}outro{# Leave Requests Approved}}}REJECT{{contagem, plural, =0{No Leave Requests Rejected}=1{1 Leave Request Rejected}outro{# Leave Requests Rejected}}} outro {{contagem, plural, =0{No Leave Requests Cancelled}=1{1 Leave Request Cancelled}outro{# Leave Requests Cancelled}}} }', 1, 'custom', NOW()),
(1068, @ptbr, 'Imposto de Renda Estadual', 1, 'custom', NOW()),
(1069, @ptbr, 'Bi semanal', 1, 'custom', NOW()),
(1070, @ptbr, 'De hora em hora', 1, 'custom', NOW()),
(1071, @ptbr, 'Mensal', 1, 'custom', NOW()),
(1072, @ptbr, 'Mensalmente no primeiro pagamento do mês', 1, 'custom', NOW()),
(1073, @ptbr, 'Semestralmente', 1, 'custom', NOW()),
(1074, @ptbr, 'Semanalmente', 1, 'custom', NOW()),
(1075, @ptbr, 'Poupança', 1, 'custom', NOW()),
(1076, @ptbr, 'Verificando', 1, 'custom', NOW()),
(1077, @ptbr, 'Adicionar Supervisor', 1, 'custom', NOW()),
(1078, @ptbr, 'Adicionar Subordinado', 1, 'custom', NOW()),
(1079, @ptbr, 'O nome de usuário já existe', 1, 'custom', NOW()),
(1080, @ptbr, '{contagem,plural, =0{No Records Imported}um{1 Record Successfully Imported}outro{ # Records Successfully Imported}}', 1, 'custom', NOW()),
(1081, @ptbr, '{contagem,plural, =0{No Records Failed to Import}um{1 Record Failed to Import}outro{ # Records Failed to Import}}', 1, 'custom', NOW()),
(1082, @ptbr, 'Linhas com falha', 1, 'custom', NOW()),
(1083, @ptbr, 'Detalhes de importação', 1, 'custom', NOW()),
(1084, @ptbr, 'Entrada registrada', 1, 'custom', NOW()),
(1085, @ptbr, 'Sa?da registrada', 1, 'custom', NOW()),
(1086, @ptbr, 'Entrada n?o registrada', 1, 'custom', NOW()),
(1087, @ptbr, 'Distribui??o de colaboradores por unidade', 1, 'custom', NOW()),
(1088, @ptbr, 'Distribui??o de colaboradores por localidade', 1, 'custom', NOW()),
(1089, @ptbr, 'N?o atribu?do', 1, 'custom', NOW()),
(1090, @ptbr, 'Colaboradores de f?rias hoje', 1, 'custom', NOW()),
(1091, @ptbr, 'Nenhum colaborador est? de f?rias hoje', 1, 'custom', NOW()),
(1092, @ptbr, 'Período de licença não definido', 1, 'custom', NOW()),
(1093, @ptbr, 'Ponto de Hoje', 1, 'custom', NOW()),
(1094, @ptbr, 'Hoje', 1, 'custom', NOW()),
(1095, @ptbr, 'Esta semana', 1, 'custom', NOW()),
(1096, @ptbr, '{lastState}:{date}em{time}(GMT{timezoneOffset})', 1, 'custom', NOW()),
(1097, @ptbr, '{lastState}: Hoje em{time}(GMT{timezoneOffset})', 1, 'custom', NOW()),
(1098, @ptbr, 'Acesso r?pido', 1, 'custom', NOW()),
(1099, @ptbr, 'Minhas a??es', 1, 'custom', NOW()),
(1100, @ptbr, '{pendingActionsCount,plural, =0{No Records Found}um{(1) Leave Request to Approve}outro{ (#) Leave Requests to Approve}}', 1, 'custom', NOW()),
(1101, @ptbr, '{pendingActionsCount,plural, =0{No Records Found}um{(1) Timesheet to Approve}outro{ (#) Timesheets to Approve}}', 1, 'custom', NOW()),
(1102, @ptbr, '{pendingActionsCount,plural, =0{No Records Found}um{(1) Performance Review to Evaluate}outro{ (#) Performance Reviews to Evaluate}}', 1, 'custom', NOW()),
(1103, @ptbr, '{pendingActionsCount,plural, =0{No Records Found}um{(1) Candidate to Interview}outro{ (#) Candidates to Interview}}', 1, 'custom', NOW()),
(1104, @ptbr, 'Nenhuma a??o pendente', 1, 'custom', NOW()),
(1105, @ptbr, '{pendingActionsCount,plural, =0{No Records Found}um{(1) Pending Self Review}outro{ (#) Pending Self Reviews}}', 1, 'custom', NOW()),
(1106, @ptbr, 'Configura??es', 1, 'custom', NOW()),
(1107, @ptbr, 'Mostrar apenas funcionários acessíveis em licença para outros usuários', 1, 'custom', NOW()),
(1108, @ptbr, 'N?o dispon?vel', 1, 'custom', NOW()),
(1109, @ptbr, 'Enviado', 1, 'custom', NOW()),
(1110, @ptbr, 'Não enviado', 1, 'custom', NOW()),
(1111, @ptbr, 'Aprovado', 1, 'custom', NOW()),
(1112, @ptbr, 'Próximos aniversários', 1, 'custom', NOW()),
(1113, @ptbr, '{anosCount,plural, =0{} um{Year}outro{Years}}', 1, 'custom', NOW()),
(1114, @ptbr, 'Feed de notícias do Buzz', 1, 'custom', NOW()),
(1115, @ptbr, 'Publicar', 1, 'custom', NOW()),
(1116, @ptbr, 'O que está em sua mente?', 1, 'custom', NOW()),
(1117, @ptbr, 'Compartilhar fotos', 1, 'custom', NOW()),
(1118, @ptbr, 'Compartilhar vídeo', 1, 'custom', NOW()),
(1120, @ptbr, '{contagem de curtidas,plural, =0{0 Likes}um{1 Like}outro{# Likes}}', 1, 'custom', NOW()),
(1121, @ptbr, '{commentCount,plural, =0{0 Comments}um{1 Comment}outro{# Comments}}', 1, 'custom', NOW()),
(1122, @ptbr, '{shareCount,plural, =0{0 Shares}um{1 Share}outro{# Shares}}', 1, 'custom', NOW()),
(1123, @ptbr, 'Escreva seu comentário...', 1, 'custom', NOW()),
(1124, @ptbr, 'Excluir postagem', 1, 'custom', NOW()),
(1125, @ptbr, 'Editar postagem', 1, 'custom', NOW()),
(1126, @ptbr, 'Postagens mais recentes', 1, 'custom', NOW()),
(1127, @ptbr, 'Postagens mais curtidas', 1, 'custom', NOW()),
(1128, @ptbr, 'Postagens mais comentadas', 1, 'custom', NOW()),
(1129, @ptbr, 'Compartilhar', 1, 'custom', NOW()),
(1130, @ptbr, 'VídeoURL', 1, 'custom', NOW()),
(1131, @ptbr, 'Colar vídeoURL', 1, 'custom', NOW()),
(1132, @ptbr, 'Adicionar fotos', 1, 'custom', NOW()),
(1133, @ptbr, 'Somente imagens do tipo ''gif'', ''png'', ''jpg'', ''jpeg'' são permitidas!', 1, 'custom', NOW()),
(1134, @ptbr, 'O tamanho máximo permitido do arquivo é 2 MB', 1, 'custom', NOW()),
(1135, @ptbr, 'Compartilhar postagem', 1, 'custom', NOW()),
(1136, @ptbr, 'Leia mais', 1, 'custom', NOW()),
(1137, @ptbr, 'Pressione Esc para', 1, 'custom', NOW()),
(1138, @ptbr, 'Como', 1, 'custom', NOW()),
(1139, @ptbr, 'Nenhuma postagem disponível', 1, 'custom', NOW()),
(1141, @ptbr, 'O item selecionado será excluído permanentemente. Tem certeza de que deseja continuar?', 1, 'custom', NOW()),
(1142, @ptbr, 'EsteURLnão é umURLválido de um vídeo ou não é suportado pelo sistema', 1, 'custom', NOW()),
(1143, @ptbr, '?ltimos comunicados', 1, 'custom', NOW()),
(1144, @ptbr, 'Nenhuma postagem adicionada', 1, 'custom', NOW()),
(1145, @ptbr, 'Primeiros passos com OrangeHRM', 1, 'custom', NOW()),
(1146, @ptbr, 'ClienteID', 1, 'custom', NOW()),
(1147, @ptbr, 'Segredo do cliente', 1, 'custom', NOW()),
(1148, @ptbr, 'RedirecionarURI', 1, 'custom', NOW()),
(1149, @ptbr, 'Lista de clientes OAuth', 1, 'custom', NOW()),
(1150, @ptbr, 'Adicionar cliente OAuth', 1, 'custom', NOW()),
(1151, @ptbr, 'Editar cliente OAuth', 1, 'custom', NOW()),
(1152, @ptbr, 'Habilitar cliente', 1, 'custom', NOW()),
(1153, @ptbr, 'Cliente Confidencial', 1, 'custom', NOW()),
(1154, @ptbr, 'Certifique-se de copiar o segredo do cliente agora. Você não poderá vê-lo novamente.', 1, 'custom', NOW()),
(1155, @ptbr, '{contagem,plural, um{Should have at least 1 character}outro{Should have at least # characters}}', 1, 'custom', NOW()),
(1156, @ptbr, '{contagem,plural, um{Should not exceed 1 character}outro{Should not exceed # characters}}', 1, 'custom', NOW()),
(1157, @ptbr, '{contagem,plural, um{Your password must contain minimum 1 lower-case letter}outro{Your password must contain minimum # lower-case letters}}', 1, 'custom', NOW()),
(1158, @ptbr, '{contagem,plural, um{Your password must contain minimum 1 upper-case letter}outro{Your password must contain minimum # upper-case letters}}', 1, 'custom', NOW()),
(1159, @ptbr, '{contagem,plural, um{Your password must contain minimum 1 number}outro{Your password must contain minimum # numbers}}', 1, 'custom', NOW()),
(1160, @ptbr, '{contagem,plural, um{Your password must contain minimum 1 special character}outro{Your password must contain minimum # special characters}}', 1, 'custom', NOW()),
(1161, @ptbr, 'Sua senha não deve conter espaços', 1, 'custom', NOW()),
(1162, @ptbr, 'Sua senha atende aos requisitos mínimos, mas pode ser adivinhada', 1, 'custom', NOW()),
(1163, @ptbr, 'Alterar senha fraca', 1, 'custom', NOW()),
(1164, @ptbr, 'Sua senha atual é fraca. Escolha uma senha mais forte.', 1, 'custom', NOW()),
(1165, @ptbr, 'Código de redefinição de senha inválido', 1, 'custom', NOW()),
(1166, @ptbr, '{clientName}gostaria de', 1, 'custom', NOW()),
(1167, @ptbr, 'Acesse e gerencie seus dados', 1, 'custom', NOW()),
(1168, @ptbr, 'Execute ações em seu nome', 1, 'custom', NOW()),
(1169, @ptbr, 'Deseja permitir o acesso?', 1, 'custom', NOW()),
(1170, @ptbr, 'Negar', 1, 'custom', NOW()),
(1171, @ptbr, 'Permitir acesso', 1, 'custom', NOW()),
(1172, @ptbr, 'Esta solicitação é inválida', 1, 'custom', NOW()),
(1173, @ptbr, 'O aplicativo móvel não está ativado. Entre em contato com o administrador do OrangeHRM.', 1, 'custom', NOW()),
(1174, @ptbr, 'Forte', 1, 'custom', NOW()),
(1175, @ptbr, 'Ajuda', 1, 'custom', NOW()),
(1176, @ptbr, 'Solicita??es', 1, 'custom', NOW()),
(1177, @ptbr, 'Eventos', 1, 'custom', NOW()),
(1178, @ptbr, 'Adicionar Evento', 1, 'custom', NOW()),
(1179, @ptbr, 'Editar evento', 1, 'custom', NOW()),
(1180, @ptbr, 'Nome do Evento', 1, 'custom', NOW()),
(1181, @ptbr, 'Tipos de despesa', 1, 'custom', NOW()),
(1182, @ptbr, 'Adicionar tipo de despesa', 1, 'custom', NOW()),
(1183, @ptbr, 'Editar tipo de despesa', 1, 'custom', NOW()),
(1184, @ptbr, 'Evento', 1, 'custom', NOW()),
(1185, @ptbr, 'Criar solicitação de reivindicação', 1, 'custom', NOW()),
(1186, @ptbr, 'Observações', 1, 'custom', NOW()),
(1187, @ptbr, 'Criar', 1, 'custom', NOW()),
(1188, @ptbr, 'Enviar solicita??o', 1, 'custom', NOW()),
(1189, @ptbr, 'ID de referência', 1, 'custom', NOW()),
(1190, @ptbr, 'Despesas', 1, 'custom', NOW()),
(1191, @ptbr, 'Tipo de despesa', 1, 'custom', NOW()),
(1192, @ptbr, 'Pagar', 1, 'custom', NOW()),
(1193, @ptbr, 'Adicionar despesa', 1, 'custom', NOW()),
(1194, @ptbr, 'Editar despesa', 1, 'custom', NOW()),
(1195, @ptbr, 'Deve ser um número válido (xxx.xx)', 1, 'custom', NOW()),
(1196, @ptbr, 'Valor total ({currencyName}):{totalAmount}', 1, 'custom', NOW()),
(1197, @ptbr, 'Data de envio', 1, 'custom', NOW()),
(1198, @ptbr, 'Ver detalhes', 1, 'custom', NOW()),
(1199, @ptbr, 'Minhas solicita??es', 1, 'custom', NOW()),
(1200, @ptbr, 'Módulo de reivindicação', 1, 'custom', NOW()),
(1201, @ptbr, 'Iniciado', 1, 'custom', NOW()),
(1202, @ptbr, 'Pago', 1, 'custom', NOW()),
(1203, @ptbr, 'Atribuir solicita??o', 1, 'custom', NOW()),
(1204, @ptbr, 'Solicita??es de colaboradores', 1, 'custom', NOW()),
(1205, @ptbr, 'Esta página está atualmente em desenvolvimento.', 1, 'custom', NOW()),
(1206, @ptbr, 'para baixar a versão estável mais recente.', 1, 'custom', NOW()),
(1207, @ptbr, 'Limpar', 1, 'custom', NOW()),
(1208, @ptbr, 'Fechar', 1, 'custom', NOW()),
(1209, @ptbr, 'ProvedorURL', 1, 'custom', NOW()),
(1210, @ptbr, 'Adicionar provedor', 1, 'custom', NOW()),
(1211, @ptbr, 'Editar provedor', 1, 'custom', NOW()),
(1212, @ptbr, 'Lista de provedores', 1, 'custom', NOW()),
(1213, @ptbr, 'Nenhum usuário encontrado', 1, 'custom', NOW()),
(1214, @ptbr, 'Vários usuários retornados', 1, 'custom', NOW()),
(1215, @ptbr, 'Quantia', 1, 'custom', NOW()),
(1216, @ptbr, 'Use o modelo de exemplo', 1, 'custom', NOW()),
(1217, @ptbr, 'Edite apenas o campo de destino', 1, 'custom', NOW()),
(1218, @ptbr, 'Não altere o modelo', 1, 'custom', NOW()),
(1219, @ptbr, 'AmostraXLIFF', 1, 'custom', NOW()),
(1220, @ptbr, 'Importar pacote de idiomas', 1, 'custom', NOW()),
(1221, @ptbr, 'O texto não será traduzido automaticamente. Você terá que importar traduções ou traduzir dentro do sistema.', 1, 'custom', NOW()),
(1222, @ptbr, 'Deve ser inferior ao salário máximo', 1, 'custom', NOW()),
(1223, @ptbr, 'Erros em pacotes de idiomas de importação', 1, 'custom', NOW()),
(1224, @ptbr, 'A sintaxe usada é inválida', 1, 'custom', NOW()),
(1225, @ptbr, 'Incompatibilidade encontrada entre espaços reservados', 1, 'custom', NOW()),
(1226, @ptbr, 'Incompatibilidade encontrada entre o espaço reservado para expressão plural', 1, 'custom', NOW()),
(1227, @ptbr, 'Incompatibilidade encontrada entre o espaço reservado para expressão selecionada', 1, 'custom', NOW()),
(1228, @ptbr, '{contagem,plural, =0{No Records Skipped}um{1 Record Skipped}outro{ # Records Skipped}}', 1, 'custom', NOW()),
(1229, @ptbr, '{contagem,plural, =0{No Errors Found}um{(1) Error Found}outro{ (#) Errors Found}}', 1, 'custom', NOW()),
(1230, @ptbr, '{contagem,plural, um{Fix Error}outro{ Fix Errors}}', 1, 'custom', NOW()),
(1231, @ptbr, 'O arquivoXLIFFnão é válido', 1, 'custom', NOW()),
(1232, @ptbr, 'O arquivoXLIFFestá vazio', 1, 'custom', NOW()),
(1233, @ptbr, 'O arquivoXLIFFnão tem o atributo do idioma de destino', 1, 'custom', NOW()),
(1234, @ptbr, 'O idioma de destino não corresponde ao idioma selecionado', 1, 'custom', NOW()),
(1235, @ptbr, 'Salve suas alterações antes de passar para a próxima página', 1, 'custom', NOW()),
(1236, @ptbr, 'Solteiro(a)', 1, 'custom', NOW()),
(1237, @ptbr, 'Casado(a)', 1, 'custom', NOW()),
(1238, @ptbr, 'Direto', 1, 'custom', NOW()),
(1239, @ptbr, 'Indireto', 1, 'custom', NOW()),
(1240, @ptbr, 'Vagas de emprego ativas', 1, 'custom', NOW()),
(1241, @ptbr, 'Atualizar', 1, 'custom', NOW()),
(1242, @ptbr, '{contar, plural, um{Accepts up to 1MB}outro{ Accepts up to #MBs}}', 1, 'custom', NOW()),
(1243, @ptbr, '{contar, plural, um{Accepts .docx, .doc, .odt, .pdf, .rtf, .txt up to 1MB}outro{ Accepts .docx, .doc, .odt, .pdf, .rtf, .txt up to #MBs}}', 1, 'custom', NOW()),
(1244, @ptbr, 'O link de redefinição de senha não foi enviado', 1, 'custom', NOW()),
(1245, @ptbr, 'O link de redefinição de senha não foi enviado devido a um erro.', 1, 'custom', NOW()),
(1246, @ptbr, 'Entre em contato com seu administrador para redefinir sua senha.', 1, 'custom', NOW()),
(1247, @ptbr, 'Sessão expirada', 1, 'custom', NOW()),
(1248, @ptbr, 'O e-mail comercial contém caracteres inválidos.', 1, 'custom', NOW())
ON DUPLICATE KEY UPDATE value=VALUES(value), customized=1, version='custom', modified_at=NOW();
UPDATE ohrm_menu_item SET menu_title='Administra??o' WHERE menu_title='Admin';
UPDATE ohrm_menu_item SET menu_title='Pessoas' WHERE menu_title='PIM';
UPDATE ohrm_menu_item SET menu_title='F?rias' WHERE menu_title='Leave';
UPDATE ohrm_menu_item SET menu_title='Ponto' WHERE menu_title='Time';
UPDATE ohrm_menu_item SET menu_title='Recrutamento' WHERE menu_title='Recruitment';
UPDATE ohrm_menu_item SET menu_title='Meus Dados' WHERE menu_title='My Info';
UPDATE ohrm_menu_item SET menu_title='Desempenho' WHERE menu_title='Performance';
UPDATE ohrm_menu_item SET menu_title='Painel' WHERE menu_title='Dashboard';
UPDATE ohrm_menu_item SET menu_title='Diret?rio' WHERE menu_title='Directory';
UPDATE ohrm_menu_item SET menu_title='Manuten??o' WHERE menu_title='Maintenance';
UPDATE ohrm_menu_item SET menu_title='Solicita??es' WHERE menu_title='Claim';
UPDATE ohrm_menu_item SET menu_title='Comunicados' WHERE menu_title='Buzz';
UPDATE ohrm_menu_item SET menu_title='Gerenciamento de usu?rios' WHERE menu_title='User Management';
UPDATE ohrm_menu_item SET menu_title='Cargos' WHERE menu_title='Job';
UPDATE ohrm_menu_item SET menu_title='Organiza??o' WHERE menu_title='Organization';
UPDATE ohrm_menu_item SET menu_title='Qualifica??es' WHERE menu_title='Qualifications';
UPDATE ohrm_menu_item SET menu_title='Nacionalidades' WHERE menu_title='Nationalities';
UPDATE ohrm_menu_item SET menu_title='Identidade visual' WHERE menu_title='Corporate Branding';
UPDATE ohrm_menu_item SET menu_title='Configura??o' WHERE menu_title='Configuration';
UPDATE ohrm_menu_item SET menu_title='Usu?rios' WHERE menu_title='Users';
UPDATE ohrm_menu_item SET menu_title='Clientes' WHERE menu_title='Customers';
UPDATE ohrm_menu_item SET menu_title='Projetos' WHERE menu_title='Projects';
UPDATE ohrm_menu_item SET menu_title='Cargos' WHERE menu_title='Job Titles';
UPDATE ohrm_menu_item SET menu_title='Faixas salariais' WHERE menu_title='Pay Grades';
UPDATE ohrm_menu_item SET menu_title='Situa??o do v?nculo' WHERE menu_title='Employment Status';
UPDATE ohrm_menu_item SET menu_title='Categorias de cargo' WHERE menu_title='Job Categories';
UPDATE ohrm_menu_item SET menu_title='Turnos de trabalho' WHERE menu_title='Work Shifts';
UPDATE ohrm_menu_item SET menu_title='Informa??es gerais' WHERE menu_title='General Information';
UPDATE ohrm_menu_item SET menu_title='Locais' WHERE menu_title='Locations';
UPDATE ohrm_menu_item SET menu_title='Estrutura' WHERE menu_title='Structure';
UPDATE ohrm_menu_item SET menu_title='Compet?ncias' WHERE menu_title='Skills';
UPDATE ohrm_menu_item SET menu_title='Escolaridade' WHERE menu_title='Education';
UPDATE ohrm_menu_item SET menu_title='Licen?as' WHERE menu_title='Licenses';
UPDATE ohrm_menu_item SET menu_title='Idiomas' WHERE menu_title='Languages';
UPDATE ohrm_menu_item SET menu_title='Associa??es' WHERE menu_title='Memberships';
UPDATE ohrm_menu_item SET menu_title='Configura??o de e-mail' WHERE menu_title='Email Configuration';
UPDATE ohrm_menu_item SET menu_title='Assinaturas de e-mail' WHERE menu_title='Email Subscriptions';
UPDATE ohrm_menu_item SET menu_title='Localiza??o' WHERE menu_title='Localization';
UPDATE ohrm_menu_item SET menu_title='Pacotes de idioma' WHERE menu_title='Language Packages';
UPDATE ohrm_menu_item SET menu_title='M?dulos' WHERE menu_title='Modules';
UPDATE ohrm_menu_item SET menu_title='Autentica??o por rede social' WHERE menu_title='Social Media Authentication';
UPDATE ohrm_menu_item SET menu_title='Registrar cliente OAuth' WHERE menu_title='Register OAuth Client';
UPDATE ohrm_menu_item SET menu_title='Configura??o LDAP' WHERE menu_title='LDAP Configuration';
UPDATE ohrm_menu_item SET menu_title='Lista de colaboradores' WHERE menu_title='Employee List';
UPDATE ohrm_menu_item SET menu_title='Adicionar colaborador' WHERE menu_title='Add Employee';
UPDATE ohrm_menu_item SET menu_title='Relat?rios' WHERE menu_title='Reports';
UPDATE ohrm_menu_item SET menu_title='Campos opcionais' WHERE menu_title='Optional Fields';
UPDATE ohrm_menu_item SET menu_title='Campos personalizados' WHERE menu_title='Custom Fields';
UPDATE ohrm_menu_item SET menu_title='Importa??o de dados' WHERE menu_title='Data Import';
UPDATE ohrm_menu_item SET menu_title='M?todos de relat?rio' WHERE menu_title='Reporting Methods';
UPDATE ohrm_menu_item SET menu_title='Motivos de desligamento' WHERE menu_title='Termination Reasons';
UPDATE ohrm_menu_item SET menu_title='Solicitar' WHERE menu_title='Apply';
UPDATE ohrm_menu_item SET menu_title='Minhas f?rias' WHERE menu_title='My Leave';
UPDATE ohrm_menu_item SET menu_title='Saldos' WHERE menu_title='Entitlements';
UPDATE ohrm_menu_item SET menu_title='Configurar' WHERE menu_title='Configure';
UPDATE ohrm_menu_item SET menu_title='Lista de f?rias' WHERE menu_title='Leave List';
UPDATE ohrm_menu_item SET menu_title='Atribuir f?rias' WHERE menu_title='Assign Leave';
UPDATE ohrm_menu_item SET menu_title='Per?odo de f?rias' WHERE menu_title='Leave Period';
UPDATE ohrm_menu_item SET menu_title='Tipos de f?rias' WHERE menu_title='Leave Types';
UPDATE ohrm_menu_item SET menu_title='Semana de trabalho' WHERE menu_title='Work Week';
UPDATE ohrm_menu_item SET menu_title='Feriados' WHERE menu_title='Holidays';
UPDATE ohrm_menu_item SET menu_title='Folhas de ponto' WHERE menu_title='Timesheets';
UPDATE ohrm_menu_item SET menu_title='Frequ?ncia' WHERE menu_title='Attendance';
UPDATE ohrm_menu_item SET menu_title='Informa??es do projeto' WHERE menu_title='Project Info';
UPDATE ohrm_menu_item SET menu_title='Minhas folhas de ponto' WHERE menu_title='My Timesheets';
UPDATE ohrm_menu_item SET menu_title='Folhas de ponto dos colaboradores' WHERE menu_title='Employee Timesheets';
UPDATE ohrm_menu_item SET menu_title='Meus registros' WHERE menu_title='My Records';
UPDATE ohrm_menu_item SET menu_title='Entrada/Sa?da' WHERE menu_title='Punch In/Out';
UPDATE ohrm_menu_item SET menu_title='Registros de colaboradores' WHERE menu_title='Employee Records';
UPDATE ohrm_menu_item SET menu_title='Relat?rios de projeto' WHERE menu_title='Project Reports';
UPDATE ohrm_menu_item SET menu_title='Relat?rios de colaboradores' WHERE menu_title='Employee Reports';
UPDATE ohrm_menu_item SET menu_title='Resumo de frequ?ncia' WHERE menu_title='Attendance Summary';
UPDATE ohrm_menu_item SET menu_title='Candidatos' WHERE menu_title='Candidates';
UPDATE ohrm_menu_item SET menu_title='Vagas' WHERE menu_title='Vacancies';
UPDATE ohrm_menu_item SET menu_title='Adicionar saldos' WHERE menu_title='Add Entitlements';
UPDATE ohrm_menu_item SET menu_title='Saldos dos colaboradores' WHERE menu_title='Employee Entitlements';
UPDATE ohrm_menu_item SET menu_title='Meus saldos' WHERE menu_title='My Entitlements';
UPDATE ohrm_menu_item SET menu_title='Relat?rio de saldos e uso de f?rias' WHERE menu_title='Leave Entitlements and Usage Report';
UPDATE ohrm_menu_item SET menu_title='Meu relat?rio de saldos e uso de f?rias' WHERE menu_title='My Leave Entitlements and Usage Report';
UPDATE ohrm_menu_item SET menu_title='Gerenciar avalia??es' WHERE menu_title='Manage Reviews';
UPDATE ohrm_menu_item SET menu_title='Meus acompanhamentos' WHERE menu_title='My Trackers';
UPDATE ohrm_menu_item SET menu_title='Acompanhamentos dos colaboradores' WHERE menu_title='Employee Trackers';
UPDATE ohrm_menu_item SET menu_title='Indicadores' WHERE menu_title='KPIs';
UPDATE ohrm_menu_item SET menu_title='Acompanhamentos' WHERE menu_title='Trackers';
UPDATE ohrm_menu_item SET menu_title='Minhas avalia??es' WHERE menu_title='My Reviews';
UPDATE ohrm_menu_item SET menu_title='Avalia??es dos colaboradores' WHERE menu_title='Employee Reviews';
UPDATE ohrm_menu_item SET menu_title='Eliminar registros' WHERE menu_title='Purge Records';
UPDATE ohrm_menu_item SET menu_title='Acessar registros' WHERE menu_title='Access Records';
UPDATE ohrm_menu_item SET menu_title='Registros de candidatos' WHERE menu_title='Candidate Records';
UPDATE ohrm_menu_item SET menu_title='Enviar solicita??o' WHERE menu_title='Submit Claim';
UPDATE ohrm_menu_item SET menu_title='Minhas solicita??es' WHERE menu_title='My Claims';
UPDATE ohrm_menu_item SET menu_title='Solicita??es de colaboradores' WHERE menu_title='Employee Claims';
UPDATE ohrm_menu_item SET menu_title='Atribuir solicita??o' WHERE menu_title='Assign Claim';
UPDATE ohrm_menu_item SET menu_title='Eventos' WHERE menu_title='Events';
UPDATE ohrm_menu_item SET menu_title='Tipos de despesa' WHERE menu_title='Expense Types';
UPDATE hs_hr_employee SET emp_firstname='Administrador', emp_middle_name='', emp_lastname='Sistema' WHERE emp_number=1;
