database:
  hostName: 127.0.0.1
  hostPort: 3306
  databaseName: cia_ferias
  privilegedDatabaseUser: root
  privilegedDatabasePassword: root
  useSameDbUserForCiaFerias: n # y/n, if this field `n` fill `ciaFeriasDatabaseUser` and `ciaFeriasDatabasePassword`
  ciaFeriasDatabaseUser: cia_ferias
  ciaFeriasDatabasePassword: cia_ferias
  isExistingDatabase: n # y/n
  enableDataEncryption: n # y/n

organization:
  name: CIA Férias
  country: BR

admin:
  adminUserName: Admin
  adminPassword: CiaFerias@2026!
  adminEmployeeFirstName: Administrador
  adminEmployeeLastName: Sistema
  workEmail: admin@cia-ferias.local
  contactNumber: ~
  registrationConsent: true

license:
  agree: y # y/n
